const CHANNEL_URL='https://www.youtube.com/@diaadiadaelo';
const SUBSCRIBE_URL='https://www.youtube.com/@diaadiadaelo?sub_confirmation=1';
const INSTAGRAM_URL='https://www.instagram.com/elo_verissimo';
const MEMBER_URL='https://www.youtube.com/channel/UCBPBaYweoBPjr8XlfOz1dwQ/join';
const PLAYLISTS=[
 {id:'PLhOZycBHbEs6cNunzaW8lPEsXR46fBmq4',title:'Escolinha da Elo | Aprenda Brincando',icon:'📚'},
 {id:'PLhOZycBHbEs48-Z1X_bN6lvUpw4Rosz2I',title:'Ache o Personagem Escondido',icon:'🔎'},
 {id:'PLhOZycBHbEs5VT6AAr2Xiv_teqn03Lwsg',title:'Maratona da Elo | Todos os Vídeos',icon:'🎬'},
 {id:'PLhOZycBHbEs6C_t7GSPeVEEl5aO7dd8gH',title:'Shows, Eventos e Personagens da Elo',icon:'🎭'},
 {id:'PLhOZycBHbEs5D4-Wqa3RNgAZYxDRZqP4i',title:'Momentos que Marcaram a História da Elo',icon:'🎉'},
 {id:'PLhOZycBHbEs4EQl6kh96zvbpq9N_Ybxbm',title:'Momentos na Escola e Apresentações da Elo',icon:'🍎'},
 {id:'PLhOZycBHbEs7Zo4Flf2SmadR9MsC4yOYO',title:'Aventuras e Passeios da Elo',icon:'🌎'},
 {id:'PLhOZycBHbEs4LjNfBDJCjhe1E_M7K1oSq',title:'Peixes da Elo',icon:'🐠'},
 {id:'PLhOZycBHbEs64afG13roQP2ZnzPx5fXd-',title:'Natal da Elo',icon:'🎄'},
 {id:'PLhOZycBHbEs5vV3X_PACKBO-irNlLhWIF',title:'Escolinha, Brincadeiras e Desafios da Elo',icon:'🎮'},
 {id:'PLhOZycBHbEs7JROD9ymRS9LreZ4MBz0wV',title:'Lives e Bate-papo',icon:'🔴'},
 {id:'PLhOZycBHbEs5yoHE1PgIDLfn08_7rd86u',title:'Shorts Divertidos da Elo',icon:'⚡'},
 {id:'PLhOZycBHbEs6Afo_8He5MhGlLcd9vXjRh',title:'Cozinha da Elo | Receitas e Diversão',icon:'🍳'}
];
const STORIES=[
 {id:'story1',title:'A Mochila Desaparecida',summary:'Organização e responsabilidade.',moral:'Guardar cada coisa no seu lugar.',pages:10},
 {id:'story2',title:'O Guarda-Chuva Rosa',summary:'Gentileza que transforma o dia.',moral:'Gentileza também é uma aventura.',pages:10},
 {id:'story3',title:'A Sementinha Misteriosa',summary:'Paciência, cuidado e descobertas.',moral:'Com amor e paciência, pequenas sementes viram grandes belezas.',pages:10},
 {id:'story4',title:'Elo e o Passarinho Perdido',summary:'Empatia e respeito aos animais.',moral:'Ajudar também é saber dar espaço.',pages:10}
];

let stars=Number(localStorage.getItem('eloStars')||0),currentStory=0,currentPage=0;
let favorites=JSON.parse(localStorage.getItem('eloFavStories')||'[]');
let readStories=JSON.parse(localStorage.getItem('eloReadStories')||'[]');
const starCount=document.getElementById('starCount');

function renderStars(){starCount.textContent=stars;renderBadges()}
function addStars(n=1,msg='Você ganhou uma estrelinha! ⭐'){stars+=n;localStorage.setItem('eloStars',stars);renderStars();toast(msg)}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1900)}
let appRestoringHistory=false,appExitArmed=false;
function currentPanelId(){return document.querySelector('.panel.active')?.id||'homePanel'}
function appStateForPanel(id,nav){return {eloApp:true,type:id==='homePanel'?'home':'panel',id,nav}}
function pushAppState(state){if(appRestoringHistory)return;const cur=history.state||{};if(cur.eloApp&&cur.type===state.type&&cur.id===state.id)return;history.pushState(state,'')}
function openPanel(id,nav,fromHistory=false){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.nav===nav));window.scrollTo({top:0,behavior:'smooth'});if(id==='storiesPanel')renderLibrary();if(id==='parentsPanel'||id==='achievementsPanel')renderBadges();if(id==='playPanel'){clearInterval(findTimer);clearTimeout(tapTimer);clearInterval(chaseInterval);trailStop()}if(id==='createPanel'){renderColoringGallery();renderPalette()}if(!fromHistory)pushAppState(appStateForPanel(id,nav))}
function appBack(){if(document.getElementById('exitConfirm')&&!document.getElementById('exitConfirm').classList.contains('hidden'))return cancelAppExit();history.back()}
function showExitConfirm(){document.getElementById('exitConfirm')?.classList.remove('hidden')}
function cancelAppExit(){document.getElementById('exitConfirm')?.classList.add('hidden')}
function confirmAppExit(){appExitArmed=true;document.getElementById('exitConfirm')?.classList.add('hidden');setTimeout(()=>history.go(-2),20);setTimeout(()=>{try{window.close()}catch(_){/* Android/PWA pode ignorar */}},350)}
function setupAppHistory(){if(history.state?.eloGuard||history.state?.eloApp)return;history.replaceState({eloGuard:true},'');history.pushState({eloApp:true,type:'home',id:'homePanel',nav:'home'},'')}
function restoreAppHistoryState(s){appRestoringHistory=true;try{document.getElementById('gameModal')?.classList.add('hidden');document.getElementById('coloringModal')?.classList.add('hidden');document.getElementById('rpgOverlay')?.classList.add('hidden');document.body.style.overflow='';clearInterval(findTimer);clearTimeout(tapTimer);clearInterval(chaseInterval);trailStop();if(!s||s.type==='home')openPanel('homePanel','home',true);else if(s.type==='panel')openPanel(s.id||'homePanel',s.nav||'home',true);else if(s.type==='game'){openPanel('playPanel','play',true);openGame(s.id,s.title,true)}else if(s.type==='coloring'){openPanel('createPanel','create',true);openColoring(Number(s.index)||0,true)}else if(s.type==='rpg'){openPanel('playPanel','play',true);openRpg(true)}}finally{appRestoringHistory=false}}
window.addEventListener('popstate',e=>{if(appExitArmed)return;if(e.state?.eloGuard){history.pushState({eloApp:true,type:'home',id:'homePanel',nav:'home'},'');restoreAppHistoryState({type:'home'});showExitConfirm();return}if(e.state?.eloApp)restoreAppHistoryState(e.state)});

let parentPendingAction=null,parentPinBuffer='',parentPinMode='verify',parentPinFirst='';
function launchExternal(url){const w=window.open(url,'_blank','noopener,noreferrer');if(!w)location.href=url}
function hasParentPin(){return /^\d{4}$/.test(localStorage.getItem('eloParentPin')||'')}
function parentUnlocked(){return sessionStorage.getItem('eloParentUnlocked')==='1'}
function updatePinDots(){document.querySelectorAll('#pinDots .pinDot').forEach((d,i)=>d.classList.toggle('on',i<parentPinBuffer.length))}
function showParentPin(message,mode='verify',action=null){parentPendingAction=action;parentPinMode=mode;parentPinBuffer='';parentPinFirst='';const modal=document.getElementById('parentPinModal');document.getElementById('pinTitle').textContent=mode.startsWith('setup')?'Criar PIN dos responsáveis':'Área dos responsáveis';document.getElementById('pinMessage').textContent=message;updatePinDots();modal.classList.remove('hidden');document.body.style.overflow='hidden'}
function closeParentPin(){document.getElementById('parentPinModal').classList.add('hidden');document.body.style.overflow='';parentPinBuffer='';parentPendingAction=null;updatePinDots()}
function finishParentAccess(){sessionStorage.setItem('eloParentUnlocked','1');const cb=parentPendingAction;document.getElementById('parentPinModal').classList.add('hidden');document.body.style.overflow='';parentPendingAction=null;parentPinBuffer='';updatePinDots();if(cb)cb()}
function requestParentAccess(action,message='Digite o PIN de 4 dígitos dos responsáveis para continuar.'){if(parentUnlocked())return action();if(!hasParentPin())return showParentPin('Crie um PIN de 4 dígitos. Ele ficará salvo somente neste aparelho.','setup1',action);showParentPin(message,'verify',action)}
function pinKey(n){if(parentPinBuffer.length>=4)return;parentPinBuffer+=n;updatePinDots();if(parentPinBuffer.length===4)processParentPin()}
function pinBackspace(){parentPinBuffer=parentPinBuffer.slice(0,-1);updatePinDots()}
function processParentPin(){if(parentPinBuffer.length!==4)return;const entered=parentPinBuffer;if(parentPinMode==='setup1'){parentPinFirst=entered;parentPinBuffer='';parentPinMode='setup2';document.getElementById('pinMessage').textContent='Repita o novo PIN para confirmar.';updatePinDots();return}if(parentPinMode==='setup2'){if(entered!==parentPinFirst){parentPinBuffer='';parentPinMode='setup1';parentPinFirst='';document.getElementById('pinMessage').textContent='Os PINs não coincidiram. Crie novamente um PIN de 4 dígitos.';updatePinDots();return}localStorage.setItem('eloParentPin',entered);finishParentAccess();toast('PIN dos responsáveis criado 🔐');return}if(parentPinMode==='change1'){parentPinFirst=entered;parentPinBuffer='';parentPinMode='change2';document.getElementById('pinMessage').textContent='Repita o novo PIN para confirmar.';updatePinDots();return}if(parentPinMode==='change2'){if(entered!==parentPinFirst){parentPinBuffer='';parentPinMode='change1';parentPinFirst='';document.getElementById('pinMessage').textContent='Os PINs não coincidiram. Tente novamente.';updatePinDots();return}localStorage.setItem('eloParentPin',entered);document.getElementById('parentPinModal').classList.add('hidden');document.body.style.overflow='';parentPinBuffer='';updatePinDots();toast('PIN alterado com sucesso 🔐');return}if(entered===localStorage.getItem('eloParentPin'))finishParentAccess();else{parentPinBuffer='';document.getElementById('pinMessage').textContent='PIN incorreto. Tente novamente.';updatePinDots()}}
function changeParentPin(){parentPinBuffer='';parentPinFirst='';parentPinMode='change1';parentPendingAction=null;document.getElementById('pinTitle').textContent='Alterar PIN';document.getElementById('pinMessage').textContent='Digite um novo PIN de 4 dígitos.';updatePinDots();document.getElementById('parentPinModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function openExternal(url){requestParentAccess(()=>launchExternal(url),'Digite o PIN dos responsáveis para abrir este link externo.')}
function openParents(){requestParentAccess(()=>openPanel('parentsPanel','parents'))}
function openMemberWithGate(){openExternal(MEMBER_URL)}
function openSubscribe(){openExternal(SUBSCRIBE_URL)}
function openInstagram(){openExternal(INSTAGRAM_URL)}
function openGame(id,title,fromHistory=false){clearInterval(findTimer);clearTimeout(tapTimer);clearInterval(chaseInterval);trailStop();document.getElementById('gameModalTitle').textContent=title;document.querySelectorAll('.gameSection').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.getElementById('gameModal').classList.remove('hidden');document.body.style.overflow='hidden';if(!fromHistory)pushAppState({eloApp:true,type:'game',id,title});if(id==='findGame')resetFind(true);if(id==='mazeGame')startMaze();if(id==='unicornChaseGame')startChase();if(id==='memoryGame')startMemory();if(id==='puzzleGame')startPuzzle(false);if(id==='tapGameSection')startTapGame();if(id==='trailGame')startTrailGame()}
function closeGame(fromHistory=false){if(!fromHistory&&history.state?.type==='game')return history.back();clearInterval(findTimer);clearTimeout(tapTimer);clearInterval(chaseInterval);trailStop();document.getElementById('gameModal').classList.add('hidden');document.body.style.overflow=''}
function openRpg(fromHistory=false){trailStop();clearInterval(findTimer);clearTimeout(tapTimer);clearInterval(chaseInterval);const frame=document.getElementById('rpgFrame');const wanted=new URL('./rpg.html?v=1.7.4',location.href).href;frame.src=wanted;document.getElementById('rpgOverlay').classList.remove('hidden');document.body.style.overflow='hidden';if(!fromHistory)pushAppState({eloApp:true,type:'rpg'})}
function closeRpg(fromHistory=false){if(!fromHistory&&history.state?.type==='rpg')return history.back();const frame=document.getElementById('rpgFrame');document.getElementById('rpgOverlay').classList.add('hidden');document.body.style.overflow='';if(frame)frame.src='about:blank';renderBadges()}
window.addEventListener('message',e=>{const d=e.data||{};if(d.type==='rpg-close')closeRpg();if(d.type==='rpg-open-youtube')openExternal(CHANNEL_URL);if(d.type==='rpg-medal')renderBadges()});
function openColoring(i,fromHistory=false){chooseColoring(i,true);if(!fromHistory)pushAppState({eloApp:true,type:'coloring',index:i})}
function closeColoring(fromHistory=false){if(!fromHistory&&history.state?.type==='coloring')return history.back();document.getElementById('coloringModal').classList.add('hidden');document.body.style.overflow='';if(typeof resetColorZoom==='function')resetColorZoom()}

const daily=[['Missão da Elo','Dê 5 pulinhos e faça uma pose engraçada!'],['Missão das cores','Ache 3 coisas cor-de-rosa perto de você.'],['Missão do sorriso','Faça alguém da família dar risada.'],['Missão movimento','Imite um sapinho por 10 segundos.'],['Missão desenho','Pinte um desenho da Elo e mostre para alguém.'],['Missão gentil','Faça uma gentileza para alguém da família.']];
const d=daily[new Date().getDate()%daily.length];
document.getElementById('dailyText').textContent=d[1];
const dailyKey='eloDaily'+new Date().toDateString();
if(localStorage.getItem(dailyKey))document.getElementById('dailyProgress').style.width='100%';
function completeDaily(){if(localStorage.getItem(dailyKey))return toast('A missão de hoje já foi concluída 💗');localStorage.setItem(dailyKey,'1');document.getElementById('dailyProgress').style.width='100%';addStars(2,'Missão concluída! +2 ⭐')}

function renderStoryStrip(){const box=document.getElementById('storyStrip');if(!box)return;box.innerHTML=STORIES.map((s,i)=>`<button class="storyCard" onclick="openStory(${i})"><div class="storyThumb" style="background-image:url('assets/stories/${s.id}-cover.webp')"><span class="numBadge">${i+1}</span><span class="heartBadge">${favorites.includes(s.id)?'♥':'♡'}</span></div><div class="storyInfo"><b>${s.title}</b><small>${s.summary}</small></div></button>`).join('')}
function renderLibrary(){const box=document.getElementById('libraryGrid');box.innerHTML=STORIES.map((s,i)=>`<article class="libCard"><div class="libCover" style="background-image:url('assets/stories/${s.id}-cover.webp')"><span class="numBadge">${i+1}</span><button class="fav ${favorites.includes(s.id)?'on':''}" onclick="toggleFav('${s.id}',event)">${favorites.includes(s.id)?'♥':'♡'}</button></div><div class="libBody"><h3>${s.title}</h3><p>${s.summary}</p><div class="libMeta"><small>📖 ${s.pages} páginas ${readStories.includes(s.id)?'• ✅ lida':''}</small><button class="btn" onclick="openStory(${i})">Ler</button></div></div></article>`).join('')}
function toggleFav(id,e){e.stopPropagation();favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('eloFavStories',JSON.stringify(favorites));renderLibrary();renderStoryStrip();toast(favorites.includes(id)?'Adicionada aos favoritos 💗':'Removida dos favoritos')}
function openStory(i){currentStory=i;currentPage=0;openPanel('readerPanel','stories');renderReader()}
function renderReader(){const s=STORIES[currentStory],page=document.getElementById('storyPage');document.getElementById('readerTitle').textContent=s.title;page.style.backgroundImage=`url('assets/stories/${s.id}.webp')`;page.style.backgroundRepeat='no-repeat';page.style.backgroundSize=`100% ${s.pages*100}%`;page.style.backgroundPosition=`center ${currentPage*(100/(s.pages-1))}%`;document.getElementById('pageCounter').textContent=`Página ${currentPage+1} de ${s.pages}`;document.getElementById('readerMoral').textContent=currentPage===s.pages-1?'✨ '+s.moral:'';document.getElementById('readerDots').innerHTML=Array.from({length:s.pages},(_,i)=>`<i class="dot ${i===currentPage?'on':''}"></i>`).join('');if(currentPage===s.pages-1&&!readStories.includes(s.id)){readStories.push(s.id);localStorage.setItem('eloReadStories',JSON.stringify(readStories));addStars(3,'História concluída! +3 ⭐');renderLibrary()}}
function nextPage(){const s=STORIES[currentStory];if(currentPage<s.pages-1){currentPage++;renderReader()}else toast('Fim da história 💗')}
function prevPage(){if(currentPage>0){currentPage--;renderReader()}else toast('Você está na primeira página')}
let touchX=0;
document.getElementById('storyPage').addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});
document.getElementById('storyPage').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(dx<-45)nextPage();if(dx>45)prevPage()},{passive:true});

function renderPlaylists(){document.getElementById('playlistGrid').innerHTML=PLAYLISTS.map(p=>`<button class="playlistCard" onclick="openExternal('https://youtube.com/playlist?list=${p.id}')"><div class="picon">${p.icon}</div><b>${p.title}</b><span>Abrir playlist no YouTube →</span></button>`).join('')}

// Game medals — bronze on easy, silver on medium, gold on hard
const MEDAL_TIERS={easy:{icon:'🥉',label:'Bronze'},medium:{icon:'🥈',label:'Prata'},hard:{icon:'🥇',label:'Ouro'}};
const MEDAL_GAMES=[
 {id:'find',icon:'⭐',name:'Olho de Águia'},
 {id:'maze',icon:'🦄',name:'Exploradora do Labirinto'},
 {id:'chase',icon:'👻',name:'Caçadora de Unicórnios'},
 {id:'memory',icon:'🧠',name:'Mestra da Memória'},
 {id:'puzzle',icon:'🧩',name:'Mestra do Quebra-cabeça'},
 {id:'tap',icon:'🎯',name:'Raio dos Números'},
 {id:'trail',icon:'✨',name:'Heroína da Trilha'}
];
const RPG_MEDALS=[
 {id:'first-step',icon:'👣',name:'Primeiro Passo'},{id:'home-explorer',icon:'🏠',name:'Casa Doce Casa'},{id:'tv-fan',icon:'📺',name:'Fã da Elo'},
 {id:'good-meal',icon:'🍎',name:'Bom Apetite'},{id:'rested',icon:'🌙',name:'Soninho Restaurador'},{id:'first-chat',icon:'💬',name:'Primeira Conversa'},
 {id:'social',icon:'🤝',name:'Amiga da Cidade'},{id:'quest',icon:'📜',name:'Primeira Missão'},{id:'first-win',icon:'✨',name:'Primeira Vitória'},
 {id:'level2',icon:'🌟',name:'Ficando Mais Forte'},{id:'level5',icon:'👑',name:'Heroína Experiente'},{id:'shopper',icon:'🛍️',name:'Primeira Compra'},
 {id:'stylish',icon:'👗',name:'Elo Estilosa'},{id:'explorer',icon:'🗺️',name:'Exploradora'},{id:'fighter10',icon:'👾',name:'Protetora do Reino'},
 {id:'rich',icon:'🪙',name:'Cofrinho Cheio'},{id:'potion',icon:'🧪',name:'Preparada'},{id:'chapter1',icon:'🏆',name:'Guardiã da Primeira Estrela'}
];
function getRpgMedals(){try{return JSON.parse(localStorage.getItem('eloRpgMedals')||'[]')}catch(_){return[]}}
function renderRpgMedals(){const box=document.getElementById('rpgMedals');if(!box)return;const got=getRpgMedals();box.innerHTML=RPG_MEDALS.map(m=>`<div class="rpgMedal ${got.includes(m.id)?'on':''}"><span>${m.icon}</span><strong>${m.name}</strong><small>${got.includes(m.id)?'Conquistada!':'Bloqueada'}</small></div>`).join('')}

function medalKey(game,level){return `eloMedal-${game}-${level}`}
function hasGameMedal(game,level){return localStorage.getItem(medalKey(game,level))==='1'}
function unlockGameMedal(game,level){const first=!hasGameMedal(game,level);if(first)localStorage.setItem(medalKey(game,level),'1');renderBadges();if(first){const gameInfo=MEDAL_GAMES.find(g=>g.id===game),tier=MEDAL_TIERS[level];setTimeout(()=>toast(`${tier.icon} ${tier.label} • ${gameInfo.name}!`),420)}return first}
function renderGameMedals(){const box=document.getElementById('gameMedals');if(!box)return;box.innerHTML=MEDAL_GAMES.map(g=>`<div class="medalGame"><div class="medalGameHead"><span>${g.icon}</span><strong>${g.name}</strong></div><div class="medalTiers">${['easy','medium','hard'].map(level=>{const t=MEDAL_TIERS[level],ok=hasGameMedal(g.id,level);return `<div class="medalTier ${ok?'on':''}"><span>${t.icon}</span><b>${level==='easy'?'Fácil':level==='medium'?'Médio':'Difícil'}</b><small>${ok?'Conquistada':'Bloqueada'}</small></div>`}).join('')}</div></div>`).join('')}

// Find the star
let findLevel='easy',findTimer=null,findLeft=20,findRounds=0;
const FIND={easy:{size:13,time:20,reward:1,count:46},medium:{size:10,time:14,reward:2,count:62},hard:{size:8,time:9,reward:3,count:78}};
const FIND_SCENES=[
 {bg:'linear-gradient(180deg,#7ed6ff 0 48%,#8fe38e 48% 75%,#f6c56b 75%)',objects:['☁️','🌷','🌳','🏠','🦋','🌼','🌻','🍄','🌿','🍎','🐞','🐝','🪁','🎈'],sparkles:['✦','✨','✧','💛','🌟','☀️']},
 {bg:'linear-gradient(180deg,#a7dcff 0 44%,#ffe0ef 44% 65%,#8ed27d 65%)',objects:['☁️','🎈','🪁','🌈','🐥','🌼','🧸','🍭','🍓','🦄','🌸','🧁','🍬','🎀'],sparkles:['✦','✨','✧','💛','🌟','☀️']},
 {bg:'linear-gradient(180deg,#6953a8 0 42%,#8f7bd5 42% 62%,#3f7b67 62%)',objects:['🌙','☁️','🦄','🎀','🍬','🍩','💜','🌸','🎠','🧁','🌳','🏰','🦋'],sparkles:['✦','✨','✧','💛','🌟','⭐']}
];
const findStage=document.getElementById('findStage');
function rand(min,max){return Math.random()*(max-min)+min}
function setFindLevel(level,btn){findLevel=level;document.querySelectorAll('[data-find]').forEach(x=>x.classList.remove('on'));btn.classList.add('on');resetFind(true)}
function buildFindScene(cfg){const scene=FIND_SCENES[Math.floor(Math.random()*FIND_SCENES.length)];findStage.innerHTML='';findStage.style.background=scene.bg;for(let i=0;i<cfg.count;i++){const el=document.createElement('div');el.className='obj';el.textContent=scene.objects[Math.floor(Math.random()*scene.objects.length)];el.style.left=rand(0,94)+'%';el.style.top=rand(1,91)+'%';el.style.fontSize=rand(15,34)+'px';el.style.opacity=String(rand(.72,1));el.style.transform=`rotate(${rand(-24,24)}deg)`;findStage.appendChild(el)}for(let i=0;i<Math.floor(cfg.count*.7);i++){const el=document.createElement('div');el.className='fake';el.textContent=scene.sparkles[Math.floor(Math.random()*scene.sparkles.length)];el.style.left=rand(1,95)+'%';el.style.top=rand(2,92)+'%';el.style.fontSize=rand(Math.max(7,cfg.size-2),cfg.size+7)+'px';findStage.appendChild(el)}const t=document.createElement('button');t.id='target';t.className='target';t.setAttribute('aria-label','estrela escondida');t.innerHTML='<span>⭐</span>';t.style.left=rand(2,94)+'%';t.style.top=rand(2,91)+'%';t.style.setProperty('--star-size',cfg.size+'px');t.style.transform=`rotate(${rand(-30,30)}deg)`;t.dataset.found='0';t.onclick=()=>{if(t.dataset.found==='1')return;t.dataset.found='1';clearInterval(findTimer);findRounds++;document.getElementById('findStatus').textContent='Achou! 🎉';addStars(FIND[findLevel].reward,`Achou! +${FIND[findLevel].reward} ⭐`);unlockGameMedal('find',findLevel);setTimeout(()=>resetFind(),850)};findStage.appendChild(t)}
function resetFind(manual=false){clearInterval(findTimer);const cfg=FIND[findLevel];buildFindScene(cfg);findLeft=cfg.time;document.getElementById('findTime').textContent=findLeft+'s';document.getElementById('findStatus').textContent=manual?'Nova estrela escondida!':'Ache a estrela!';findTimer=setInterval(()=>{findLeft--;document.getElementById('findTime').textContent=findLeft+'s';if(findLeft<=0){clearInterval(findTimer);document.getElementById('findStatus').textContent='O tempo acabou!';setTimeout(()=>resetFind(),900)}},1000)}

// Maze game — three difficulty levels
const MAZE_LEVELS={easy:{size:9,reward:2},medium:{size:11,reward:3},hard:{size:13,reward:5}};
let mazeLevel='easy',mazeSize=MAZE_LEVELS.easy.size,mazeMap=[],mazePlayer={x:1,y:1},mazeGoal={x:mazeSize-2,y:mazeSize-2},mazeMoves=0,mazeWon=false,mazeRewarded=false;
function setMazeLevel(level,btn){mazeLevel=level;document.querySelectorAll('[data-maze]').forEach(x=>x.classList.remove('on'));btn.classList.add('on');startMaze()}
function makeMaze(size){const grid=Array.from({length:size},()=>Array(size).fill('#'));const dirs=[[2,0],[-2,0],[0,2],[0,-2]];function dig(x,y){grid[y][x]='.';const order=shuffle(dirs);for(const [dx,dy] of order){const nx=x+dx,ny=y+dy;if(nx<=0||ny<=0||nx>=size-1||ny>=size-1||grid[ny][nx]!=='#')continue;grid[y+dy/2][x+dx/2]='.';dig(nx,ny)}}dig(1,1);grid[1][1]='S';grid[size-2][size-2]='G';return grid}
function startMaze(){const cfg=MAZE_LEVELS[mazeLevel];mazeSize=cfg.size;mazeMap=makeMaze(mazeSize);mazeMoves=0;mazeWon=false;mazeRewarded=false;for(let y=0;y<mazeMap.length;y++){for(let x=0;x<mazeMap[y].length;x++){if(mazeMap[y][x]==='S'){mazePlayer={x,y};mazeMap[y][x]='.'}if(mazeMap[y][x]==='G'){mazeGoal={x,y};mazeMap[y][x]='.'}}}document.getElementById('mazeBoard').style.gridTemplateColumns=`repeat(${mazeSize},1fr)`;document.getElementById('mazeMoves').textContent='Movimentos: 0';document.getElementById('mazeStatus').textContent='Encontre o unicórnio!';renderMaze()}
function renderMaze(){const board=document.getElementById('mazeBoard');board.innerHTML='';mazeMap.forEach((row,y)=>row.forEach((cell,x)=>{const d=document.createElement('div');const isPlayer=mazePlayer.x===x&&mazePlayer.y===y,isGoal=mazeGoal.x===x&&mazeGoal.y===y;d.className='mazeCell '+(cell==='#'?'wall':'path')+(isPlayer?' player':'')+(isGoal?' goal':'');if(isPlayer)d.textContent='👧';else if(isGoal)d.textContent='🦄';else if(cell==='#'&&(x+y)%7===0)d.textContent='🌿';board.appendChild(d)}))}
function moveMaze(dx,dy){if(!mazeMap.length||mazeWon)return;const nx=mazePlayer.x+dx,ny=mazePlayer.y+dy;if(ny<0||ny>=mazeMap.length||nx<0||nx>=mazeMap[0].length)return;if(mazeMap[ny][nx]==='#'){toast('Parede! Tente outro caminho 😊');return}mazePlayer={x:nx,y:ny};mazeMoves++;document.getElementById('mazeMoves').textContent='Movimentos: '+mazeMoves;renderMaze();if(nx===mazeGoal.x&&ny===mazeGoal.y){mazeWon=true;document.getElementById('mazeStatus').textContent='Elo chegou ao unicórnio! 🦄✨';if(!mazeRewarded){mazeRewarded=true;const cfg=MAZE_LEVELS[mazeLevel];addStars(cfg.reward,`Labirinto concluído! +${cfg.reward} ⭐`);unlockGameMedal('maze',mazeLevel)}}else document.getElementById('mazeStatus').textContent='Continue procurando o caminho.'}
let mazeTouchStart=null;
const mazeBoard=document.getElementById('mazeBoard');
mazeBoard.addEventListener('touchstart',e=>{const t=e.changedTouches[0];mazeTouchStart={x:t.clientX,y:t.clientY}},{passive:true});
mazeBoard.addEventListener('touchend',e=>{if(!mazeTouchStart)return;const t=e.changedTouches[0],dx=t.clientX-mazeTouchStart.x,dy=t.clientY-mazeTouchStart.y;mazeTouchStart=null;if(Math.abs(dx)<20&&Math.abs(dy)<20)return;if(Math.abs(dx)>Math.abs(dy))moveMaze(dx>0?1:-1,0);else moveMaze(0,dy>0?1:-1)},{passive:true});


// Caça aos Unicórnios — arena aberta com espaço real para fugir
const CHASE_LEVELS={easy:{size:13,total:4,ghostMs:2200,reward:2,smart:.62,startDelay:2200},medium:{size:15,total:5,ghostMs:1550,reward:3,smart:.82,startDelay:1800},hard:{size:17,total:6,ghostMs:1100,reward:5,smart:1,startDelay:1400}};
let chaseLevel='easy',chaseSize=CHASE_LEVELS.easy.size,chaseTotal=CHASE_LEVELS.easy.total,chaseMap=[],chasePlayer={x:1,y:1},chaseGhost={x:chaseSize-2,y:chaseSize-2},chaseUnicorns=[],chaseInterval=null,chaseWon=false,chaseLost=false,chaseCollected=0;
function setChaseLevel(level,btn){chaseLevel=level;document.querySelectorAll('[data-chase]').forEach(x=>x.classList.remove('on'));btn.classList.add('on');startChase()}
function chaseKey(x,y){return `${x},${y}`}
function makeChaseMap(){const n=chaseSize,grid=Array.from({length:n},(_,y)=>Array.from({length:n},(_,x)=>(x===0||y===0||x===n-1||y===n-1)?'#':'.'));const mid=Math.floor(n/2);const reserved=(x,y)=>x<=2&&y<=2||x>=n-3&&y>=n-3||x===1||y===1||x===n-2||y===n-2||x===mid||y===mid;for(let y=3;y<n-3;y+=4){for(let x=3;x<n-3;x+=4){if(reserved(x,y))continue;const shape=(x+y)%3;if(shape===0){grid[y][x]='#';if(x+1<n-2&&!reserved(x+1,y))grid[y][x+1]='#'}else if(shape===1){grid[y][x]='#';if(y+1<n-2&&!reserved(x,y+1))grid[y+1][x]='#'}else grid[y][x]='#'}}for(let i=0;i<Math.floor(n/3);i++){const x=2+Math.floor(Math.random()*(n-4)),y=2+Math.floor(Math.random()*(n-4));if(!reserved(x,y)&&Math.random()>.35)grid[y][x]='#'}grid[1][1]='.';grid[n-2][n-2]='.';return grid}
function chaseOpenCells(){const cells=[];for(let y=1;y<chaseSize-1;y++)for(let x=1;x<chaseSize-1;x++)if(chaseMap[y][x]==='.')cells.push({x,y});return cells}
function chaseDistance(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)}
function startChase(){clearInterval(chaseInterval);const cfg=CHASE_LEVELS[chaseLevel];chaseSize=cfg.size;chaseTotal=cfg.total;chaseMap=makeChaseMap();chasePlayer={x:1,y:1};chaseGhost={x:chaseSize-2,y:chaseSize-2};chaseWon=false;chaseLost=false;chaseCollected=0;let candidates=shuffle(chaseOpenCells().filter(p=>chaseDistance(p,chasePlayer)>Math.max(5,Math.floor(chaseSize/3))&&chaseDistance(p,chaseGhost)>4));chaseUnicorns=[];for(const c of candidates){if(chaseUnicorns.every(u=>chaseDistance(u,c)>3)){chaseUnicorns.push(c);if(chaseUnicorns.length>=chaseTotal)break}}if(chaseUnicorns.length<chaseTotal)chaseUnicorns=candidates.slice(0,chaseTotal);document.getElementById('chaseBoard').style.gridTemplateColumns=`repeat(${chaseSize},1fr)`;document.getElementById('chaseStatus').textContent='Corra pela arena e pegue os unicórnios!';document.getElementById('chaseCount').textContent=`🦄 0/${chaseTotal}`;renderChase();setTimeout(()=>{if(!chaseWon&&!chaseLost&&!document.getElementById('gameModal').classList.contains('hidden'))chaseInterval=setInterval(moveChaseGhost,cfg.ghostMs)},cfg.startDelay)}
function renderChase(){const board=document.getElementById('chaseBoard');if(!board)return;board.innerHTML='';const uni=new Set(chaseUnicorns.map(p=>chaseKey(p.x,p.y)));for(let y=0;y<chaseSize;y++){for(let x=0;x<chaseSize;x++){const d=document.createElement('div'),wall=chaseMap[y][x]==='#',player=chasePlayer.x===x&&chasePlayer.y===y,ghost=chaseGhost.x===x&&chaseGhost.y===y,unicorn=uni.has(chaseKey(x,y));d.className='chaseCell '+(wall?'wall':'path')+(player?' player':'')+(ghost?' ghost':'')+(unicorn?' unicorn':'');if(player)d.textContent='👧';else if(ghost)d.textContent='👻';else if(unicorn)d.textContent='🦄';else if(!wall&&(x*7+y*11)%31===0)d.textContent='🌸';board.appendChild(d)}}}
function collectChaseUnicorn(){const k=chaseKey(chasePlayer.x,chasePlayer.y),before=chaseUnicorns.length;chaseUnicorns=chaseUnicorns.filter(p=>chaseKey(p.x,p.y)!==k);if(chaseUnicorns.length<before){chaseCollected++;document.getElementById('chaseCount').textContent=`🦄 ${chaseCollected}/${chaseTotal}`;toast('Unicórnio encontrado! 🦄✨');if(chaseCollected>=chaseTotal){chaseWon=true;clearInterval(chaseInterval);document.getElementById('chaseStatus').textContent='Você pegou todos! 🎉';const cfg=CHASE_LEVELS[chaseLevel];addStars(cfg.reward,`Todos os unicórnios encontrados! +${cfg.reward} ⭐`);unlockGameMedal('chase',chaseLevel)}}}
function chaseCaught(){if(chaseWon||chaseLost)return;chaseLost=true;clearInterval(chaseInterval);document.getElementById('chaseStatus').textContent='O fantasminha encontrou a Elo! 👻';toast('Quase! Agora há bastante espaço para fugir — tente outra rota 💗');renderChase()}
function moveChase(dx,dy){if(chaseWon||chaseLost||!chaseMap.length)return;const nx=chasePlayer.x+dx,ny=chasePlayer.y+dy;if(ny<0||ny>=chaseSize||nx<0||nx>=chaseSize||chaseMap[ny][nx]==='#')return;chasePlayer={x:nx,y:ny};collectChaseUnicorn();if(chasePlayer.x===chaseGhost.x&&chasePlayer.y===chaseGhost.y)return chaseCaught();renderChase()}
function chaseNeighbors(pos){return [[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:pos.x+dx,y:pos.y+dy})).filter(p=>p.x>0&&p.y>0&&p.x<chaseSize-1&&p.y<chaseSize-1&&chaseMap[p.y][p.x]!== '#')}
function chasePathStep(){const q=[chaseGhost],seen=new Set([chaseKey(chaseGhost.x,chaseGhost.y)]),parent=new Map(),dirs=[[1,0],[-1,0],[0,1],[0,-1]];let found=false;for(let qi=0;qi<q.length&&!found;qi++){const cur=q[qi];for(const [dx,dy] of dirs){const nx=cur.x+dx,ny=cur.y+dy,k=chaseKey(nx,ny);if(nx<0||ny<0||nx>=chaseSize||ny>=chaseSize||chaseMap[ny][nx]==='#'||seen.has(k))continue;seen.add(k);parent.set(k,cur);q.push({x:nx,y:ny});if(nx===chasePlayer.x&&ny===chasePlayer.y){found=true;break}}}if(!found)return chaseGhost;let cur={...chasePlayer};while(true){const p=parent.get(chaseKey(cur.x,cur.y));if(!p)return chaseGhost;if(p.x===chaseGhost.x&&p.y===chaseGhost.y)return cur;cur=p}}
function moveChaseGhost(){if(chaseWon||chaseLost)return;const cfg=CHASE_LEVELS[chaseLevel];let next;if(Math.random()<=cfg.smart)next=chasePathStep();else{const opts=shuffle(chaseNeighbors(chaseGhost)).filter(p=>!(p.x===chasePlayer.x&&p.y===chasePlayer.y));next=opts[0]||chaseGhost}chaseGhost={x:next.x,y:next.y};if(chaseGhost.x===chasePlayer.x&&chaseGhost.y===chasePlayer.y)return chaseCaught();renderChase()}
let chaseTouchStart=null;
const chaseBoard=document.getElementById('chaseBoard');
chaseBoard.addEventListener('touchstart',e=>{const t=e.changedTouches[0];chaseTouchStart={x:t.clientX,y:t.clientY}},{passive:true});
chaseBoard.addEventListener('touchend',e=>{if(!chaseTouchStart)return;const t=e.changedTouches[0],dx=t.clientX-chaseTouchStart.x,dy=t.clientY-chaseTouchStart.y;chaseTouchStart=null;if(Math.abs(dx)<20&&Math.abs(dy)<20)return;if(Math.abs(dx)>Math.abs(dy))moveChase(dx>0?1:-1,0);else moveChase(0,dy>0?1:-1)},{passive:true});
window.addEventListener('keydown',e=>{if(document.getElementById('gameModal').classList.contains('hidden'))return;let move=null;if(e.key==='ArrowUp')move=[0,-1];if(e.key==='ArrowDown')move=[0,1];if(e.key==='ArrowLeft')move=[-1,0];if(e.key==='ArrowRight')move=[1,0];if(!move)return;if(document.getElementById('mazeGame').classList.contains('active'))moveMaze(...move);else if(document.getElementById('unicornChaseGame').classList.contains('active'))moveChase(...move)});


// Memory game — 8 / 16 / 32 cards with illustrated Elo themes
const MEMORY_IMAGES=[
 {src:'assets/memory-cards/card-01.webp',label:'Vídeos'},
 {src:'assets/memory-cards/card-02.webp',label:'Shorts'},
 {src:'assets/memory-cards/card-03.webp',label:'Brincadeiras'},
 {src:'assets/memory-cards/card-04.webp',label:'Culinária'},
 {src:'assets/memory-cards/card-05.webp',label:'Escolinha'},
 {src:'assets/memory-cards/card-06.webp',label:'Médica'},
 {src:'assets/memory-cards/card-07.webp',label:'Viagem'},
 {src:'assets/memory-cards/card-08.webp',label:'Shows'},
 {src:'assets/memory-cards/card-09.webp',label:'Personagens'},
 {src:'assets/memory-cards/card-10.webp',label:'Animais'},
 {src:'assets/memory-cards/card-11.webp',label:'Esportes'},
 {src:'assets/memory-cards/card-12.webp',label:'Unicórnio'},
 {src:'assets/memory-cards/card-13.webp',label:'Pintura'},
 {src:'assets/memory-cards/card-14.webp',label:'Leitura'},
 {src:'assets/memory-cards/card-15.webp',label:'Música'},
 {src:'assets/memory-cards/card-16.webp',label:'Aventuras'}
];
const MEMORY_LEVELS={easy:4,medium:8,hard:16};
let memoryLevel='easy',memoryOpen=[],memoryLock=false,matched=0,memoryMoves=0,memoryTotal=8;
function setMemoryLevel(level,btn){memoryLevel=level;document.querySelectorAll('[data-memory]').forEach(x=>x.classList.remove('on'));btn.classList.add('on');startMemory()}
function startMemory(){const pairs=MEMORY_LEVELS[memoryLevel];const chosen=shuffle(MEMORY_IMAGES).slice(0,pairs).map((x,i)=>({...x,key:'elo'+i}));const cards=shuffle(chosen.flatMap(x=>[x,x]));memoryTotal=cards.length;memoryOpen=[];memoryLock=false;matched=0;memoryMoves=0;const box=document.getElementById('memory');box.className='memory '+memoryLevel;box.style.gridTemplateColumns='repeat(4,1fr)';box.innerHTML='';document.getElementById('memoryStatus').textContent='Encontre os pares!';document.getElementById('memoryMoves').textContent='Jogadas: 0';cards.forEach(card=>{const b=document.createElement('button');b.className='mem';b.dataset.key=card.key;b.dataset.src=card.src;b.setAttribute('aria-label','Carta de memória fechada');b.onclick=()=>flip(b);box.appendChild(b)})}
function showMemImage(b){const d=document.createElement('div');d.className='memPic';d.style.backgroundImage=`url('${b.dataset.src}')`;b.innerHTML='';b.appendChild(d)}
function hideMemImage(b){b.innerHTML=''}
function flip(b){if(memoryLock||b.classList.contains('done')||b.classList.contains('open'))return;b.classList.add('open');showMemImage(b);memoryOpen.push(b);if(memoryOpen.length===2){memoryLock=true;memoryMoves++;document.getElementById('memoryMoves').textContent='Jogadas: '+memoryMoves;setTimeout(()=>{const[a,c]=memoryOpen;if(a.dataset.key===c.dataset.key){a.classList.add('done');c.classList.add('done');matched+=2;if(matched===memoryTotal){document.getElementById('memoryStatus').textContent='Você encontrou todos! 🎉';if(memoryLevel==='hard')localStorage.setItem('eloMemoryHardWon','1');addStars(memoryLevel==='hard'?5:memoryLevel==='medium'?3:2,'Memória completa! ⭐');unlockGameMedal('memory',memoryLevel)}}else{a.classList.remove('open');c.classList.remove('open');hideMemImage(a);hideMemImage(c)}memoryOpen=[];memoryLock=false},650)}}

// Puzzle game — tap two pieces to swap them
const PUZZLE_LEVELS={easy:3,medium:4,hard:5};
const PUZZLE_IMAGES=Array.from({length:16},(_,i)=>`assets/puzzle/puzzle-${String(i+1).padStart(2,'0')}.webp`);
let puzzleLevel='easy',puzzleImageIndex=0,puzzleOrder=[],puzzleSelected=-1,puzzleMoves=0,puzzleRewarded=false,puzzleComplete=false;
function setPuzzleLevel(level,btn){puzzleLevel=level;document.querySelectorAll('[data-puzzle]').forEach(x=>x.classList.remove('on'));btn.classList.add('on');startPuzzle(false)}
function renderPuzzleChoices(){const box=document.getElementById('puzzleChoices');if(!box)return;box.innerHTML=PUZZLE_IMAGES.map((src,i)=>`<button class="puzzleChoice ${i===puzzleImageIndex?'on':''}" onclick="choosePuzzleImage(${i})"><img src="${src}" alt="Foto ${i+1} da Elo"></button>`).join('')}
function choosePuzzleImage(i){puzzleImageIndex=i;startPuzzle(false)}
function makePuzzleOrder(total){let a=Array.from({length:total},(_,i)=>i);do{a=shuffle(a)}while(a.every((v,i)=>v===i));return a}
function startPuzzle(randomPhoto=false){const n=PUZZLE_LEVELS[puzzleLevel];if(randomPhoto)puzzleImageIndex=(puzzleImageIndex+1+Math.floor(Math.random()*(PUZZLE_IMAGES.length-1)))%PUZZLE_IMAGES.length;puzzleOrder=makePuzzleOrder(n*n);puzzleSelected=-1;puzzleMoves=0;puzzleRewarded=false;puzzleComplete=false;const prev=document.getElementById('puzzlePreview');if(prev)prev.src=PUZZLE_IMAGES[puzzleImageIndex];document.getElementById('puzzleStatus').textContent='Monte a foto!';document.getElementById('puzzleMoves').textContent='Jogadas: 0';document.getElementById('puzzleCompleteNote').classList.add('hidden');renderPuzzleChoices();renderPuzzle()}
function piecePosition(piece,n){const row=Math.floor(piece/n),col=piece%n;const x=n===1?0:(col/(n-1))*100,y=n===1?0:(row/(n-1))*100;return `${x}% ${y}%`}
function renderPuzzle(){const n=PUZZLE_LEVELS[puzzleLevel],board=document.getElementById('puzzleBoard');if(!board)return;board.style.gridTemplateColumns=`repeat(${n},1fr)`;board.classList.toggle('completed',puzzleComplete);board.innerHTML='';puzzleOrder.forEach((piece,pos)=>{const b=document.createElement('button');b.className='puzzlePiece'+(puzzleSelected===pos?' selected':'')+(piece===pos?' correct':'');b.style.backgroundImage=`url('${PUZZLE_IMAGES[puzzleImageIndex]}')`;b.style.backgroundSize=`${n*100}% ${n*100}%`;b.style.backgroundPosition=piecePosition(piece,n);b.setAttribute('aria-label',`Peça ${pos+1}`);b.disabled=puzzleComplete;b.onclick=()=>tapPuzzlePiece(pos);board.appendChild(b)})}
function tapPuzzlePiece(pos){if(puzzleComplete)return;if(puzzleSelected<0){puzzleSelected=pos;document.getElementById('puzzleStatus').textContent='Agora escolha onde colocar essa peça.';renderPuzzle();return}if(puzzleSelected===pos){puzzleSelected=-1;document.getElementById('puzzleStatus').textContent='Escolha uma peça.';renderPuzzle();return}const a=puzzleSelected;[puzzleOrder[a],puzzleOrder[pos]]=[puzzleOrder[pos],puzzleOrder[a]];puzzleSelected=-1;puzzleMoves++;document.getElementById('puzzleMoves').textContent='Jogadas: '+puzzleMoves;const solved=puzzleOrder.every((v,i)=>v===i);if(solved){puzzleComplete=true;renderPuzzle();document.getElementById('puzzleStatus').textContent='Quebra-cabeça completo! 🎉';document.getElementById('puzzleCompleteNote').classList.remove('hidden');if(!puzzleRewarded){puzzleRewarded=true;localStorage.setItem('eloPuzzleWon','1');addStars(puzzleLevel==='hard'?5:puzzleLevel==='medium'?3:2,'Quebra-cabeça completo! ⭐');unlockGameMedal('puzzle',puzzleLevel)}}else{renderPuzzle();document.getElementById('puzzleStatus').textContent='Muito bem! Continue montando.'}}

// Tap the number — 10 correct answers complete each level
const TAP_LEVELS={easy:{start:5000,min:3000,step:100,reward:2},medium:{start:3500,min:1800,step:90,reward:3},hard:{start:2500,min:900,step:80,reward:5}},TAP_GOAL=10;
let tapLevel='easy',tapTarget=1,tapScore=0,tapTimer=null,tapRound=0,tapDelay=TAP_LEVELS.easy.start,tapWon=false;
function setTapLevel(level,btn){tapLevel=level;document.querySelectorAll('[data-tap]').forEach(x=>x.classList.remove('on'));btn.classList.add('on');startTapGame()}
function buildTapRound(){clearTimeout(tapTimer);if(tapWon)return;tapRound++;tapTarget=Math.floor(Math.random()*9)+1;document.getElementById('tapPrompt').textContent=`Toque no número ${tapTarget} antes que ele mude!`;const nums=Array.from({length:9},(_,i)=>i+1).sort(()=>Math.random()-.5);document.getElementById('tapGame').innerHTML=nums.map(n=>`<button class="tapNum" onclick="tapAnswer(${n})">${n}</button>`).join('');const cfg=TAP_LEVELS[tapLevel];tapDelay=Math.max(cfg.min,cfg.start-tapScore*cfg.step);document.getElementById('tapTimeText').textContent=(tapDelay/1000).toFixed(1).replace('.',',')+'s';const bar=document.getElementById('tapTimerBar');bar.style.transition='none';bar.style.transform='scaleX(1)';requestAnimationFrame(()=>requestAnimationFrame(()=>{bar.style.transition=`transform ${tapDelay}ms linear`;bar.style.transform='scaleX(0)'}));tapTimer=setTimeout(()=>{toast('Mudou! Seja mais rápido 😄');buildTapRound()},tapDelay)}
function startTapGame(){clearTimeout(tapTimer);tapScore=0;tapRound=0;tapWon=false;document.getElementById('tapScore').textContent=`Acertos: 0/${TAP_GOAL}`;buildTapRound()}
function tapAnswer(n){if(tapWon)return;if(n===tapTarget){tapScore++;document.getElementById('tapScore').textContent=`Acertos: ${tapScore}/${TAP_GOAL}`;if(tapScore>=TAP_GOAL){tapWon=true;clearTimeout(tapTimer);const bar=document.getElementById('tapTimerBar');bar.style.transition='none';bar.style.transform='scaleX(1)';document.getElementById('tapPrompt').textContent='Desafio concluído! 🎉';document.getElementById('tapGame').innerHTML='';const cfg=TAP_LEVELS[tapLevel];addStars(cfg.reward,`10 acertos! +${cfg.reward} ⭐`);unlockGameMedal('tap',tapLevel);return}if(tapScore%3===0)addStars(1,'Boa sequência! +1 ⭐');else toast('Acertou! 🎯');buildTapRound()}else toast('Ops! Esse não era o número 😊')}



// Premium game — Elo na Trilha Encantada
const TRAIL_LEVELS={easy:{speed:1.05,jump:18.7,bossHp:6,reward:4,spawnMin:118,spawnVar:52,collectMin:38,collectVar:30,bossAttack:145,bossRest:125,bossShot:66},medium:{speed:1.55,jump:19.1,bossHp:8,reward:5,spawnMin:86,spawnVar:38,collectMin:31,collectVar:26,bossAttack:165,bossRest:105,bossShot:52},hard:{speed:2.05,jump:19.5,bossHp:10,reward:6,spawnMin:64,spawnVar:30,collectMin:25,collectVar:21,bossAttack:185,bossRest:90,bossShot:43}};
let trailLevel='easy',trailAnim=0,trailTick=0,trailCanvas=document.getElementById('trailCanvas'),trailCtx=trailCanvas.getContext('2d');
let trailRunning=false,trailLast=0,trailState=null;
const trailUI={phase:document.getElementById('trailPhase'),lives:document.getElementById('trailLives'),collected:document.getElementById('trailCollected'),score:document.getElementById('trailScore'),status:document.getElementById('trailStatus'),mode:document.getElementById('trailMode'),bossBar:document.getElementById('trailBossBar'),bossFill:document.getElementById('trailBossFill')};
function setTrailLevel(level,btn){trailLevel=level;document.querySelectorAll('[data-trail]').forEach(x=>x.classList.remove('on'));if(btn)btn.classList.add('on');restartTrailRun()}
function baseTrailState(){return {mode:'ready',phase:1,lives:3,score:0,totalCollected:0,nextLifeAt:100,phaseCollected:0,phaseGoal:18,phaseDistance:0,phaseDistanceGoal:2400,bossHp:0,bossMaxHp:0,bossShotCd:0,bossPattern:'attack',bossPatternTimer:0,bossVulnerable:false,gameOver:false,messageShown:false,player:{x:110,y:0,vy:0,w:58,h:76,jumpBuffer:0,inv:0},ground:340,worldSpeed:TRAIL_LEVELS[trailLevel].speed,spawnTimer:0,collectTimer:0,entities:[],projectiles:[],effects:[],bossProjectiles:[],boss:null,medalGiven:false}};
function restartTrailRun(){trailStop();trailState=baseTrailState();prepareTrailPhase();drawTrailScene(0);syncTrailHud();trailUI.status.textContent='Fase 1 • A aventura recomeçou!'}
function startTrailGame(){if(!trailState||trailState.lives<=0||trailState.gameOver)restartTrailRun();trailStop();trailState.worldSpeed=TRAIL_LEVELS[trailLevel].speed+(trailState.phase-1)*0.06;trailRunning=true;trailLast=performance.now();trailUI.status.textContent=isTrailBossPhase()?`Fase ${trailState.phase} • Desvie dos ataques!`:`Fase ${trailState.phase} • Corra com a Elo e pegue os objetos brilhantes!`;trailAnim=requestAnimationFrame(trailLoop)}
function trailStop(){trailRunning=false;if(trailAnim)cancelAnimationFrame(trailAnim);trailAnim=0}
function trailJump(){if(!trailState||!trailRunning)return;const p=trailState.player;const onGround=p.y>=trailState.ground-p.h-4;if(onGround){p.y=trailState.ground-p.h-1;p.vy=-TRAIL_LEVELS[trailLevel].jump;p.jumpBuffer=0}else{p.jumpBuffer=11}}
function trailMagic(){if(!trailState||!trailRunning)return;if(trailState.mode!=='boss'){toast('Guarde o poder para o chefão! 💖');return}if(!trailState.bossVulnerable){toast('Espere o chefão parar de atacar! 👻');return}const p=trailState.player;if(p.y>=trailState.ground-p.h-10){toast('Pule e use Poder no ar! ⤴️💖');return}trailState.projectiles.push({x:p.x+p.w-6,y:p.y+28,vx:11.5,size:20,alive:true});}
function isTrailBossPhase(){return trailState&&trailState.phase%5===0}
function prepareTrailPhase(){if(!trailState)return;trailState.entities=[];trailState.projectiles=[];trailState.effects=[];trailState.bossProjectiles=[];trailState.phaseCollected=0;trailState.phaseDistance=0;const pacing=TRAIL_LEVELS[trailLevel];trailState.spawnTimer=pacing.spawnMin+35;trailState.collectTimer=pacing.collectMin;trailState.player.y=trailState.ground-trailState.player.h;trailState.player.vy=0;trailState.player.inv=0;trailState.mode=isTrailBossPhase()?'boss':'run';trailState.phaseGoal=(isTrailBossPhase()?0:16+trailState.phase*2);trailState.phaseDistanceGoal=2400+trailState.phase*220;trailState.worldSpeed=TRAIL_LEVELS[trailLevel].speed+(trailState.phase-1)*0.06;trailState.boss=null;trailState.bossHp=0;trailState.bossMaxHp=0;trailState.bossVulnerable=false;trailState.bossPattern='attack';trailState.bossPatternTimer=pacing.bossAttack||150;trailState.bossShotCd=28;trailState.gameOver=false;trailState.messageShown=false;if(isTrailBossPhase()){const hp=TRAIL_LEVELS[trailLevel].bossHp+Math.max(0,Math.floor(trailState.phase/5)-1);trailState.boss={x:745,y:110,w:118,h:118,phase:0,float:0,hitFlash:0};trailState.bossHp=hp;trailState.bossMaxHp=hp;}syncTrailHud()}
function syncTrailHud(){if(!trailState)return;trailUI.phase.textContent=trailState.phase;trailUI.lives.textContent='💗 '+trailState.lives;trailUI.collected.textContent=`${trailState.totalCollected}/${trailState.nextLifeAt}`;trailUI.score.textContent=trailState.score;trailUI.mode.textContent=isTrailBossPhase()?'Modo chefão':'Modo aventura';if(trailState.mode==='boss'){trailUI.bossBar.classList.add('show');trailUI.bossFill.style.width=((trailState.bossHp/Math.max(1,trailState.bossMaxHp))*100)+'%'}else trailUI.bossBar.classList.remove('show')}
function trailLoop(ts){if(!trailRunning||!trailState)return;const dt=Math.min(1.6,(ts-trailLast)/16.6667);trailLast=ts;trailTick+=dt;updateTrail(dt);drawTrailScene(dt);trailAnim=requestAnimationFrame(trailLoop)}
function updateTrail(dt){const s=trailState,p=s.player,gravity=0.9; if(p.jumpBuffer>0)p.jumpBuffer--; p.vy+=gravity*dt; p.y+=p.vy*dt; if(p.y>s.ground-p.h){p.y=s.ground-p.h;p.vy=0;if(p.jumpBuffer>0){p.jumpBuffer=0;p.vy=-TRAIL_LEVELS[trailLevel].jump}} if(p.inv>0)p.inv-=dt;
 if(s.mode==='run'){const cfg=TRAIL_LEVELS[trailLevel];s.phaseDistance+=s.worldSpeed*dt*3; s.spawnTimer-=dt; s.collectTimer-=dt; if(s.spawnTimer<=0){spawnTrailObstacle(); s.spawnTimer=Math.max(42,cfg.spawnMin+Math.random()*cfg.spawnVar-Math.min(14,s.phase*.8))} if(s.collectTimer<=0){spawnTrailCollectible(); s.collectTimer=cfg.collectMin+Math.random()*cfg.collectVar} }
 if(s.mode==='boss')updateTrailBoss(dt);
 updateTrailEntities(dt); updateTrailProjectiles(dt); updateTrailEffects(dt); if(s.mode==='run'&&s.phaseDistance>=s.phaseDistanceGoal&&s.phaseCollected>=s.phaseGoal){completeTrailPhase()} syncTrailHud()}
function spawnTrailObstacle(){const themes=['mushroom','crate','crystal','bush'];const type=themes[Math.floor(Math.random()*themes.length)];const h=type==='crate'?48:type==='crystal'?60:type==='bush'?44:42;const w=type==='crate'?46:type==='crystal'?36:type==='bush'?52:40;trailState.entities.push({kind:'obstacle',type,x:950+Math.random()*80,y:trailState.ground-h,w,h})}
function spawnTrailCollectible(){const kind=Math.random()<0.2?'unicorn':'star';const arc=Math.random();let y=trailState.ground-110-Math.random()*120;if(arc>.6)y=trailState.ground-170-Math.random()*75;trailState.entities.push({kind:'collectible',type:kind,x:930+Math.random()*60,y,w:kind==='unicorn'?32:28,h:kind==='unicorn'?32:28,spin:Math.random()*6.28})}
function updateTrailEntities(dt){const s=trailState,p=s.player; s.entities.forEach(e=>{e.x-=s.worldSpeed*dt*3.2;if(e.spin!=null)e.spin+=0.08*dt}); s.entities=s.entities.filter(e=>e.x+e.w>-60); for(const e of [...s.entities]){if(rectHit(p,e,16)){if(e.kind==='collectible'){collectTrailItem(e)} else if(p.inv<=0){trailDamage(1,'Cuidado com o obstáculo!')}}}}
function collectTrailItem(e){const s=trailState; s.entities=s.entities.filter(x=>x!==e); s.phaseCollected++; s.totalCollected++; s.score+=e.type==='unicorn'?20:10; s.effects.push({x:e.x,y:e.y,text:e.type==='unicorn'?'🦄':'⭐',t:42}); if(s.totalCollected>=s.nextLifeAt){s.lives++; s.nextLifeAt+=100; toast('Vida extra! 💗')} if(s.phaseCollected>=s.phaseGoal&&s.mode==='run')trailUI.status.textContent='Objetivo da fase concluído! Continue até o final ✨'}
function updateTrailBoss(dt){const s=trailState,b=s.boss;if(!b)return;const cfg=TRAIL_LEVELS[trailLevel];b.float+=0.05*dt;b.hitFlash=Math.max(0,b.hitFlash-dt);if(b.x>660)b.x-=0.6*dt;s.bossPatternTimer-=dt;if(s.bossPattern==='attack'){s.bossVulnerable=false;trailUI.status.textContent='Chefão atacando! Desvie e espere a abertura 👻';s.bossShotCd-=dt;if(s.bossShotCd<=0){s.bossShotCd=cfg.bossShot;const shotType=Math.random()<0.35?'orb':'ghost';s.bossProjectiles.push({type:shotType,x:b.x+22,y:b.y+55+Math.sin(b.float)*12,vx:4.2+Math.min(1.5,s.phase*.08),vy:shotType==='orb'?0:(Math.random()-.5)*.25,w:shotType==='orb'?28:34,h:shotType==='orb'?28:34});}if(s.bossPatternTimer<=0){s.bossPattern='rest';s.bossPatternTimer=cfg.bossRest;s.bossVulnerable=true;s.bossProjectiles=[];trailUI.status.textContent='AGORA! Pule e use Poder! ✨';}}else{s.bossVulnerable=true;trailUI.status.textContent='AGORA! Pule e use Poder! ✨';if(s.bossPatternTimer<=0){s.bossPattern='attack';s.bossPatternTimer=cfg.bossAttack;s.bossVulnerable=false;s.bossShotCd=32;trailUI.status.textContent='Ele voltou a atacar! Desvie!';}}for(const pr of s.bossProjectiles){pr.x-=pr.vx*dt;pr.y+=pr.vy*dt;}s.bossProjectiles=s.bossProjectiles.filter(pr=>pr.x+pr.w>-40);for(const pr of [...s.bossProjectiles])if(rectHit(s.player,{x:pr.x,y:pr.y,w:pr.w,h:pr.h},10)&&s.player.inv<=0){s.bossProjectiles=s.bossProjectiles.filter(x=>x!==pr);trailDamage(1,'O fantasma acertou a Elo!')}}
function updateTrailProjectiles(dt){const s=trailState;for(const pr of s.projectiles){pr.x+=pr.vx*dt;pr.alive=pr.x<980;}s.projectiles=s.projectiles.filter(pr=>pr.alive);if(s.mode==='boss'&&s.boss){for(const pr of [...s.projectiles]){if(rectHit({x:pr.x,y:pr.y,w:pr.size,h:pr.size},{x:s.boss.x,y:s.boss.y,w:s.boss.w,h:s.boss.h},14)){s.projectiles=s.projectiles.filter(x=>x!==pr);if(!s.bossVulnerable){s.effects.push({x:s.boss.x+40,y:s.boss.y+20,text:'🛡️',t:24});toast('Ele está protegido. Espere a abertura!');continue}s.bossHp--;s.score+=20;s.boss.hitFlash=8;s.effects.push({x:s.boss.x+40,y:s.boss.y+20,text:'💥',t:30});if(s.bossHp<=0){defeatTrailBoss();break}}}}}
function updateTrailEffects(dt){trailState.effects.forEach(f=>{f.y-=.7*dt;f.t-=dt});trailState.effects=trailState.effects.filter(f=>f.t>0)}
function completeTrailPhase(){const s=trailState; trailStop(); s.score+=50+s.phase*5; trailUI.status.textContent=`Fase ${s.phase} concluída!`; addStars(1,`Fase ${s.phase} concluída! +1 ⭐`); setTimeout(()=>{s.phase++; prepareTrailPhase(); startTrailGame()},850)}
function defeatTrailBoss(){const s=trailState; trailStop(); s.score+=180; trailUI.status.textContent='Chefão derrotado! 🎉'; addStars(TRAIL_LEVELS[trailLevel].reward,`Chefão vencido! +${TRAIL_LEVELS[trailLevel].reward} ⭐`); if(!s.medalGiven){unlockGameMedal('trail',trailLevel);s.medalGiven=true}
 setTimeout(()=>{s.phase++; prepareTrailPhase(); startTrailGame()},1100)}
function trailDamage(amount,msg){const s=trailState,p=s.player;if(p.inv>0||s.gameOver)return;s.lives=Math.max(0,s.lives-amount);p.inv=36;toast(msg);syncTrailHud();if(s.lives<=0){s.gameOver=true;trailStop();trailUI.status.textContent='Fim de jogo! Voltando para a fase 1...';setTimeout(()=>{restartTrailRun();startTrailGame()},1200);}}
function rectHit(a,b,pad=0){return a.x+pad<b.x+b.w&&a.x+a.w-pad>b.x&&a.y+pad<b.y+b.h&&a.y+a.h-pad>b.y}
function drawTrailScene(dt){const ctx=trailCtx,s=trailState||baseTrailState(); ctx.clearRect(0,0,trailCanvas.width,trailCanvas.height);ctx.filter='saturate(1.2) contrast(1.06)'; const phase=s.phase||1; const bossMode=s.mode==='boss'; const sky=ctx.createLinearGradient(0,0,0,trailCanvas.height); const skySets=[['#89dbff','#f7f2ff'],['#98ddff','#fff3ca'],['#6f66d9','#ffb8d0'],['#88dff3','#ffe8ff']][phase%4]; sky.addColorStop(0,skySets[0]); sky.addColorStop(1,skySets[1]); ctx.fillStyle=sky; ctx.fillRect(0,0,trailCanvas.width,trailCanvas.height); drawClouds(ctx,phase); drawSunMoon(ctx,phase); drawFarMountains(ctx,phase); drawMagicCastle(ctx,phase); drawHills(ctx,phase); drawGround(ctx,phase); if(phase%3===1&&!bossMode)drawRainbow(ctx); if(bossMode)drawBossArenaGlow(ctx);
 if(s.entities)for(const e of s.entities)drawTrailEntity(ctx,e); if(s.bossProjectiles)for(const p of s.bossProjectiles)drawBossProjectile(ctx,p); if(s.projectiles)for(const p of s.projectiles)drawMagicHeart(ctx,p.x,p.y,p.size||18); if(s.boss)drawGhostBoss(ctx,s.boss,s.boss.hitFlash>0); drawPlayerElo(ctx,s.player||{x:110,y:264,w:58,h:76},(s.player&&s.player.inv>0&&Math.floor(s.player.inv)%4<2)); if(s.effects)for(const f of s.effects){ctx.save();ctx.globalAlpha=Math.min(1,f.t/30);ctx.font='28px system-ui';ctx.fillText(f.text,f.x,f.y);ctx.restore()} if(!trailRunning&&trailState&&trailUI.status.textContent.startsWith('Toque em iniciar')){ctx.save();ctx.fillStyle='rgba(255,255,255,.75)';ctx.fillRect(250,160,400,80);ctx.fillStyle='#6949b4';ctx.font='900 26px system-ui';ctx.textAlign='center';ctx.fillText('Pronta para a aventura?',450,210);ctx.restore()}ctx.filter='none'}
function drawClouds(ctx,phase){for(let i=0;i<5;i++){const x=(i*210-(trailTick*8*(i%2?1.1:.8))%1100)+40,y=40+(i%3)*24;ctx.fillStyle='rgba(255,255,255,.78)';ctx.beginPath();ctx.arc(x,y,22,0,Math.PI*2);ctx.arc(x+20,y-8,17,0,Math.PI*2);ctx.arc(x+42,y,20,0,Math.PI*2);ctx.fill();}}
function drawSunMoon(ctx,phase){ctx.save();if(phase%4===2){ctx.fillStyle='#ffe28c';ctx.beginPath();ctx.arc(120,74,34,0,Math.PI*2);ctx.fill()}else if(phase%4===3){ctx.fillStyle='#fff5b3';ctx.beginPath();ctx.arc(120,74,28,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(111,102,217,.75)';ctx.beginPath();ctx.arc(132,68,25,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#fff5cc';ctx.beginPath();ctx.arc(120,74,34,0,Math.PI*2);ctx.fill();}ctx.restore()}
function drawFarMountains(ctx,phase){ctx.fillStyle=phase%4===3?'#6b60ba':'#b9b0e7';ctx.beginPath();ctx.moveTo(0,250); for(let i=0;i<=10;i++){ctx.lineTo(i*95,180+Math.sin(i*1.4+trailTick*.01)*34)} ctx.lineTo(900,330);ctx.lineTo(0,330);ctx.closePath();ctx.fill(); ctx.fillStyle=phase%4===3?'#8b7fd1':'#d9cef6';ctx.beginPath();ctx.moveTo(0,280); for(let i=0;i<=9;i++){ctx.lineTo(i*110,220+Math.cos(i*1.2+trailTick*.015)*24)} ctx.lineTo(900,340);ctx.lineTo(0,340);ctx.closePath();ctx.fill();}
function drawMagicCastle(ctx,phase){ctx.save();ctx.translate(690,150);ctx.fillStyle=phase%4===3?'rgba(255,255,255,.22)':'rgba(255,255,255,.34)';ctx.fillRect(-8,0,90,118);ctx.fillStyle='#f7d1ef';ctx.fillRect(0,30,74,88);ctx.fillStyle='#c794f0';ctx.fillRect(10,-10,14,56);ctx.fillRect(50,-22,14,68);ctx.fillStyle='#f2b445';ctx.beginPath();ctx.moveTo(7,-10);ctx.lineTo(17,-32);ctx.lineTo(27,-10);ctx.fill();ctx.beginPath();ctx.moveTo(47,-22);ctx.lineTo(57,-44);ctx.lineTo(67,-22);ctx.fill();ctx.fillStyle='#8e61dc';ctx.fillRect(30,74,15,44);ctx.restore();}
function drawHills(ctx,phase){ctx.fillStyle='#84cf83';ctx.beginPath();ctx.moveTo(0,280); for(let i=0;i<=8;i++){ctx.quadraticCurveTo(i*120+60,230+Math.sin(i+trailTick*.02)*18,(i+1)*120,285)} ctx.lineTo(900,440);ctx.lineTo(0,440);ctx.closePath();ctx.fill(); ctx.fillStyle='#6cbc6a';ctx.beginPath();ctx.moveTo(0,325); for(let i=0;i<=9;i++){ctx.quadraticCurveTo(i*100+40,300+Math.cos(i+trailTick*.025)*16,(i+1)*100,330)} ctx.lineTo(900,440);ctx.lineTo(0,440);ctx.closePath();ctx.fill();}
function drawGround(ctx,phase){ctx.fillStyle='#866341';ctx.fillRect(0,trailState?trailState.ground+48:388,900,52); ctx.fillStyle='#9be284';ctx.fillRect(0,trailState?trailState.ground+38:378,900,12); for(let i=0;i<20;i++){ctx.fillStyle=i%2?'#ffe69a':'#f6a2c7';ctx.beginPath();ctx.arc(i*48+10,trailState.ground+34+Math.sin(i)*2,3.5,0,Math.PI*2);ctx.fill();}}
function drawRainbow(ctx){ctx.save();ctx.globalAlpha=.3;const cx=190,cy=270;['#ff6b99','#ffa94d','#ffe066','#8ce99a','#74c0fc','#b197fc'].forEach((c,i)=>{ctx.strokeStyle=c;ctx.lineWidth=10;ctx.beginPath();ctx.arc(cx,cy,160-i*16,Math.PI,Math.PI*2);ctx.stroke()});ctx.restore()}
function drawBossArenaGlow(ctx){const g=ctx.createRadialGradient(710,160,10,710,160,240);g.addColorStop(0,'rgba(255,255,255,.55)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(470,0,430,330)}
function drawTrailEntity(ctx,e){if(e.kind==='collectible'){ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h/2);ctx.rotate(Math.sin(e.spin||0)*0.2); if(e.type==='unicorn'){ctx.font='28px system-ui';ctx.fillText('🦄',-14,10)} else {ctx.font='26px system-ui';ctx.fillText('⭐',-12,10)} ctx.restore(); return;} ctx.save(); if(e.type==='crate'){ctx.fillStyle='#c69058';ctx.fillRect(e.x,e.y,e.w,e.h);ctx.strokeStyle='#8b5d35';ctx.lineWidth=4;ctx.strokeRect(e.x+2,e.y+2,e.w-4,e.h-4);ctx.beginPath();ctx.moveTo(e.x+6,e.y+6);ctx.lineTo(e.x+e.w-6,e.y+e.h-6);ctx.moveTo(e.x+e.w-6,e.y+6);ctx.lineTo(e.x+6,e.y+e.h-6);ctx.stroke();}
 else if(e.type==='crystal'){ctx.fillStyle='#b47dff';ctx.beginPath();ctx.moveTo(e.x+e.w/2,e.y);ctx.lineTo(e.x+e.w,e.y+e.h*.4);ctx.lineTo(e.x+e.w*.7,e.y+e.h);ctx.lineTo(e.x+e.w*.3,e.y+e.h);ctx.lineTo(e.x,e.y+e.h*.4);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(255,255,255,.35)';ctx.fillRect(e.x+e.w*.45,e.y+8,6,e.h-14)}
 else if(e.type==='bush'){ctx.fillStyle='#4da06f';ctx.beginPath();ctx.ellipse(e.x+16,e.y+20,18,20,0,0,Math.PI*2);ctx.ellipse(e.x+32,e.y+18,18,20,0,0,Math.PI*2);ctx.ellipse(e.x+43,e.y+22,16,18,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a8ecae';ctx.fillRect(e.x+20,e.y+28,4,10)}
 else {ctx.fillStyle='#f24f9f';ctx.beginPath();ctx.arc(e.x+14,e.y+14,12,0,Math.PI*2);ctx.arc(e.x+26,e.y+18,14,0,Math.PI*2);ctx.fillStyle='#f45ea8';ctx.fill();ctx.fillStyle='#fff29b';ctx.fillRect(e.x+18,e.y+24,6,14)} ctx.restore()}
function drawBossProjectile(ctx,p){ctx.save(); if(p.type==='ghost'){ctx.font='30px system-ui';ctx.fillText('👻',p.x,p.y+26)} else {const g=ctx.createRadialGradient(p.x+14,p.y+14,2,p.x+14,p.y+14,14);g.addColorStop(0,'#fff');g.addColorStop(.45,'#d6b2ff');g.addColorStop(1,'#8f63ff');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x+14,p.y+14,14,0,Math.PI*2);ctx.fill();} ctx.restore()}
function drawMagicHeart(ctx,x,y,size){ctx.save();ctx.translate(x,y);ctx.fillStyle='#ff6fae';ctx.beginPath();ctx.moveTo(0,size*.28);ctx.bezierCurveTo(0,-size*.05,-size*.42,-size*.06,-size*.42,size*.22);ctx.bezierCurveTo(-size*.42,size*.45,-size*.12,size*.62,0,size*.8);ctx.bezierCurveTo(size*.12,size*.62,size*.42,size*.45,size*.42,size*.22);ctx.bezierCurveTo(size*.42,-size*.06,0,-size*.05,0,size*.28);ctx.fill();ctx.restore()}
function drawGhostBoss(ctx,b,flash){ctx.save();ctx.translate(b.x,b.y+Math.sin(b.float)*10);ctx.globalAlpha=.96;ctx.fillStyle=flash?'#ffd0f2':'#f1e6ff';ctx.beginPath();ctx.arc(58,40,34,Math.PI,0);ctx.lineTo(92,92);for(let i=0;i<5;i++)ctx.quadraticCurveTo(84-i*14,102,77-i*14,92);ctx.lineTo(24,92);for(let i=0;i<4;i++)ctx.quadraticCurveTo(18+i*12,102,12+i*12,92);ctx.closePath();ctx.fill();ctx.fillStyle='#6d59b8';ctx.beginPath();ctx.arc(45,42,6,0,Math.PI*2);ctx.arc(71,42,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c77be8';ctx.lineWidth=4;ctx.beginPath();ctx.arc(58,58,14,.2,Math.PI-.2);ctx.stroke();ctx.font='28px system-ui';ctx.fillText('👑',46,16);ctx.restore()}
function drawPlayerElo(ctx,p,blink){ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=blink?.45:1;
 // cabelo cacheado alto e volumoso, inspirado na personagem da capa
 ctx.fillStyle='#5b3527';
 for(const [cx,cy,r] of [[28,17,19],[15,17,9],[42,16,10],[42,2,10],[48,-6,10],[42,-14,9],[33,-11,9],[52,3,8]]){ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill()}
 // laço rosa
 ctx.fillStyle='#ff70b3';ctx.beginPath();ctx.ellipse(37,-6,9,6,-.4,0,Math.PI*2);ctx.ellipse(50,-5,9,6,.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff4f9d';ctx.beginPath();ctx.arc(44,-5,4,0,Math.PI*2);ctx.fill();
 // rosto
 ctx.fillStyle='#efbd9b';ctx.beginPath();ctx.arc(29,25,17,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2f2544';ctx.beginPath();ctx.arc(23,24,2.6,0,Math.PI*2);ctx.arc(35,24,2.6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(22.2,23.2,.8,0,Math.PI*2);ctx.arc(34.2,23.2,.8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#d57da4';ctx.lineWidth=2;ctx.beginPath();ctx.arc(29,31,7,.15,Math.PI-.15);ctx.stroke();
 // camiseta e vestido/short roxo-rosa da capa
 ctx.fillStyle='#ff78ad';ctx.beginPath();ctx.moveTo(17,42);ctx.quadraticCurveTo(29,38,41,42);ctx.lineTo(45,62);ctx.lineTo(13,62);ctx.closePath();ctx.fill();ctx.fillStyle='#7a4fc5';ctx.beginPath();ctx.moveTo(13,61);ctx.lineTo(45,61);ctx.lineTo(40,78);ctx.lineTo(18,78);ctx.closePath();ctx.fill();ctx.fillStyle='#ffd65b';ctx.font='13px system-ui';ctx.fillText('★',25,58);
 // mochila lateral
 ctx.fillStyle='#8e4fbe';ctx.beginPath();ctx.roundRect(42,47,13,20,4);ctx.fill();ctx.fillStyle='#ffd65b';ctx.font='10px system-ui';ctx.fillText('★',44,61);
 // braços e pernas
 ctx.fillStyle='#efbd9b';ctx.fillRect(9,46,7,19);ctx.fillRect(42,46,7,19);ctx.fillRect(19,77,7,15);ctx.fillRect(33,77,7,15);ctx.fillStyle='#f6b5d1';ctx.fillRect(18,88,10,5);ctx.fillRect(32,88,10,5);ctx.restore()}
trailCanvas.addEventListener('pointerdown',e=>{e.preventDefault();trailJump()});
window.addEventListener('keydown',e=>{if(document.getElementById('gameModal').classList.contains('hidden'))return;if(document.getElementById('trailGame').classList.contains('active')){if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();trailJump()} if(e.code==='KeyZ'||e.code==='Enter'){e.preventDefault();trailMagic()}}});
restartTrailRun();

// Quiz
const QUESTIONS={
 easy:[
  ['Qual animal faz “miau”?',['Cachorro','Gato','Pato'],1,'Animais'],['Qual cor aparece no céu em um dia sem nuvens?',['Azul','Marrom','Preto'],0,'Cores'],['Quanto é 2 + 2?',['3','4','5'],1,'Números'],['Qual destes vive na água?',['Peixe','Leão','Galinha'],0,'Animais'],['Qual letra começa a palavra ELO?',['A','E','O'],1,'Letras'],['Quantos dedos temos em uma mão?',['3','5','8'],1,'Corpo'],['Qual fruta costuma ser amarela?',['Banana','Morango','Uva'],0,'Frutas'],['Qual destes é uma forma redonda?',['Círculo','Triângulo','Quadrado'],0,'Formas'],['Qual número vem depois do 6?',['5','7','9'],1,'Números'],['Qual animal late?',['Gato','Cachorro','Peixe'],1,'Animais'],['Misturando azul e amarelo, qual cor aparece?',['Verde','Vermelho','Preto'],0,'Cores'],['Quantas rodas tem uma bicicleta comum?',['1','2','4'],1,'Conhecimentos'],['Qual é o contrário de grande?',['Pequeno','Alto','Largo'],0,'Palavras'],['Qual destes é usado para escrever?',['Lápis','Prato','Sapato'],0,'Objetos'],['Qual estação costuma ser mais fria?',['Verão','Inverno','Primavera'],1,'Natureza'],['Qual número é maior?',['3','8','5'],1,'Números'],['Qual dessas atitudes é gentil?',['Ajudar alguém','Empurrar alguém','Gritar com alguém'],0,'Boas atitudes'],['Qual parte do corpo usamos para ouvir?',['Olhos','Ouvidos','Nariz'],1,'Corpo'],['Qual destes cresce em uma árvore?',['Maçã','Bola','Colher'],0,'Natureza'],['Qual letra vem depois do B?',['C','A','D'],0,'Letras']
 ],
 medium:[
  ['Quanto é 7 + 5?',['10','12','13'],1,'Matemática'],['Qual palavra está escrita corretamente?',['Caza','Casa','Cassa'],1,'Português'],['Se você tem 10 balas e dá 3, quantas sobram?',['7','6','8'],0,'Matemática'],['Qual destes animais é mamífero?',['Golfinho','Tubarão','Polvo'],0,'Animais'],['Qual planeta onde vivemos?',['Marte','Terra','Júpiter'],1,'Natureza'],['Qual é a metade de 10?',['2','5','8'],1,'Matemática'],['Qual palavra rima com “gato”?',['Pato','Bola','Flor'],0,'Português'],['Quantos lados tem um triângulo?',['3','4','5'],0,'Formas'],['O que uma planta precisa para crescer?',['Água e luz','Só brinquedos','Escuridão total'],0,'Natureza'],['Qual é o dobro de 4?',['6','8','10'],1,'Matemática'],['Qual palavra começa com o mesmo som de “bola”?',['Boca','Casa','Dado'],0,'Português'],['Qual destes é um inseto?',['Borboleta','Gato','Sapo'],0,'Animais'],['Que número falta: 2, 4, 6, __?',['7','8','10'],1,'Lógica'],['Se hoje é segunda-feira, amanhã será?',['Domingo','Terça-feira','Sábado'],1,'Tempo'],['Qual objeto mede a temperatura?',['Termômetro','Régua','Relógio'],0,'Conhecimentos'],['Qual atitude protege a natureza?',['Jogar lixo no chão','Reciclar','Desperdiçar água'],1,'Boas atitudes'],['Quanto é 15 - 6?',['9','8','10'],0,'Matemática'],['Qual palavra tem 3 sílabas?',['Sol','Boneca','Pão'],1,'Português'],['Qual destes não é fruta?',['Maçã','Cenoura','Pera'],1,'Alimentos'],['Qual sequência está em ordem crescente?',['5,4,3','2,4,6','9,7,8'],1,'Lógica']
 ],
 hard:[
  ['Quanto é 8 × 3?',['18','24','32'],1,'Matemática'],['Qual é o resultado de 36 ÷ 6?',['5','6','7'],1,'Matemática'],['Qual palavra é sinônimo de “feliz”?',['Alegre','Bravo','Cansado'],0,'Português'],['Qual número completa: 3, 6, 9, 12, __?',['14','15','16'],1,'Lógica'],['Uma dúzia corresponde a quantas unidades?',['10','12','20'],1,'Matemática'],['Qual destes animais é anfíbio?',['Sapo','Águia','Cavalo'],0,'Animais'],['Qual é a capital do Brasil?',['Brasília','Rio de Janeiro','São Paulo'],0,'Conhecimentos'],['Quantos minutos existem em uma hora?',['30','60','100'],1,'Tempo'],['Qual palavra é o oposto de “rápido”?',['Lento','Forte','Claro'],0,'Português'],['Se um livro tem 20 páginas e você leu 12, faltam quantas?',['8','10','12'],0,'Matemática'],['Qual é o próximo número: 1, 4, 7, 10, __?',['12','13','14'],1,'Lógica'],['Qual destes órgãos bombeia sangue pelo corpo?',['Coração','Pulmão','Estômago'],0,'Corpo'],['Qual é 25 + 17?',['40','42','43'],1,'Matemática'],['Qual palavra está no plural?',['Menina','Meninas','Menino'],1,'Português'],['Se três crianças dividem 12 figurinhas igualmente, cada uma recebe?',['3','4','6'],1,'Matemática'],['O que acontece com a água quando congela?',['Vira gelo','Vira fumaça','Desaparece'],0,'Natureza'],['Qual número é primo?',['9','11','15'],1,'Matemática'],['Qual frase demonstra empatia?',['Não me importo','Posso ajudar você?','Saia daqui'],1,'Boas atitudes'],['Quantos centímetros formam um metro?',['10','100','1000'],1,'Medidas'],['Qual destas palavras é um verbo?',['Correr','Azul','Casa'],0,'Português']
 ]
};
let quizLevel='easy',quizDeck=[],quizPos=0,quizCorrect=0;
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function startQuiz(level='easy'){quizLevel=level;document.querySelectorAll('.levelBtn').forEach(b=>b.classList.toggle('on',b.dataset.level===level));quizDeck=shuffle(QUESTIONS[level]).slice(0,10);quizPos=0;quizCorrect=0;renderQuiz()}
function renderQuiz(){const box=document.getElementById('quiz');if(quizPos>=quizDeck.length){const reward=Math.max(1,Math.floor(quizCorrect/3));box.innerHTML=`<div class="quizEnd"><strong>${quizCorrect}/10 acertos 🎉</strong><p class="muted">Rodada concluída sem repetir perguntas.</p><button class="btn" onclick="startQuiz('${quizLevel}')">Nova rodada</button></div>`;addStars(reward,`Escolinha concluída! +${reward} ⭐`);return}const q=quizDeck[quizPos];box.innerHTML=`<div class="quizTop"><span class="quizProgress">Pergunta ${quizPos+1}/10 • ${q[3]}</span><span class="quizProgress">Acertos: ${quizCorrect}</span></div><div class="quiz-q">${q[0]}</div><div class="answers">${q[1].map((x,i)=>`<button class="ans" onclick="answerQuiz(${i})">${x}</button>`).join('')}</div>`}
function answerQuiz(i){const q=quizDeck[quizPos];if(i===q[2]){quizCorrect++;toast('Acertou! ⭐');quizPos++;setTimeout(renderQuiz,250)}else toast('Quase! Tente outra resposta 😊')}

// Coloring
const COLORING=Array.from({length:10},(_,i)=>`assets/coloring/color-${i+1}.webp`);
const PALETTE=['#ff6fae','#ff4f8b','#ff8aa8','#ffd866','#ffbf3f','#f28b4b','#ff6b6b','#a756f5','#7756d8','#5f7bff','#61c9ef','#00bcd4','#67c98e','#00b894','#5cc08a','#8d5a3b','#c97f53','#9ea7ad','#404040','#000000','#ffffff','#d4a5ff','#a3d8ff','#f7b2d9','#b8f2e6','#ffe8a3','#f1c0a8','#caffbf','#ffc6ff','#bde0fe'];
let colorIndex=0,color='#ff6fae',baseTemplate=null,colorHistory=[];
const COLOR_HISTORY_LIMIT=6;
const canvas=document.getElementById('draw');
const ctx=canvas.getContext('2d',{willReadFrequently:true});
const colorViewport=document.getElementById('colorViewport');
const colorCanvasWrap=document.getElementById('colorCanvasWrap');
let colorZoom=1,colorBaseDisplay=600,colorPointers=new Map(),colorGesture=null,colorDragMoved=false,colorDragStart=null;
function renderColoringGallery(){const g=document.getElementById('coloringGallery');g.innerHTML=COLORING.map((src,i)=>`<button class="templateBtn ${i===colorIndex?'on':''}" onclick="openColoring(${i})"><img src="${src}" alt="Desenho ${i+1}"></button>`).join('');const c=document.getElementById('coloringCountText');if(c)c.textContent=`${COLORING.length} desenhos novos da Elo. Toque em um para abrir em tela cheia.`}
function renderPalette(){const p=document.getElementById('palette');p.innerHTML=PALETTE.map(c=>`<button class="color ${color===c?'on':''}" style="background:${c}" onclick="setColor('${c}')" aria-label="cor"></button>`).join('')}
function setColor(c){color=c;renderPalette();toast('Cor escolhida! Agora toque no desenho 🎨')}
function fitImage(img){const ratio=Math.min(canvas.width/img.width,canvas.height/img.height);const w=img.width*ratio,h=img.height*ratio,x=(canvas.width-w)/2,y=(canvas.height-h)/2;ctx.drawImage(img,x,y,w,h)}
function normalizeTemplate(){const image=ctx.getImageData(0,0,canvas.width,canvas.height),d=image.data;for(let i=0;i<d.length;i+=4){const lum=(d[i]+d[i+1]+d[i+2])/3;if(lum<215){d[i]=d[i+1]=d[i+2]=0;d[i+3]=255}else{d[i]=d[i+1]=d[i+2]=255;d[i+3]=255}}ctx.putImageData(image,0,0)}
function drawBase(){ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);if(baseTemplate)fitImage(baseTemplate);normalizeTemplate();colorHistory=[]}
function chooseColoring(i,showModal=false){colorIndex=i;const img=new Image();img.onload=()=>{baseTemplate=img;drawBase();renderColoringGallery();renderPalette();if(showModal){document.getElementById('coloringModal').classList.remove('hidden');document.body.style.overflow='hidden';requestAnimationFrame(()=>resetColorZoom())}toast('Desenho pronto! Use zoom se precisar e toque para pintar. 🖍️')};img.src=COLORING[i]}
function getPointerPos(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width-1,Math.floor((e.clientX-r.left)*(canvas.width/r.width)))),y:Math.max(0,Math.min(canvas.height-1,Math.floor((e.clientY-r.top)*(canvas.height/r.height))))}}
function hexToRgb(hex){const c=hex.replace('#','');const n=parseInt(c.length===3?c.split('').map(x=>x+x).join(''):c,16);return[(n>>16)&255,(n>>8)&255,n&255]}
function colorMatch(d,i,target,tol=18){return Math.abs(d[i]-target[0])<=tol&&Math.abs(d[i+1]-target[1])<=tol&&Math.abs(d[i+2]-target[2])<=tol&&d[i+3]===target[3]}
function fillAt(x,y){const image=ctx.getImageData(0,0,canvas.width,canvas.height),d=image.data,w=image.width,h=image.height;const start=(y*w+x)*4;const target=[d[start],d[start+1],d[start+2],d[start+3]];if(target[0]<30&&target[1]<30&&target[2]<30)return;const fill=hexToRgb(color);if(Math.abs(target[0]-fill[0])<4&&Math.abs(target[1]-fill[1])<4&&Math.abs(target[2]-fill[2])<4)return;colorHistory.push(ctx.getImageData(0,0,w,h));if(colorHistory.length>COLOR_HISTORY_LIMIT)colorHistory.shift();const matches=(px,py)=>{if(px<0||py<0||px>=w||py>=h)return false;return colorMatch(d,(py*w+px)*4,target)};const paint=(px,py)=>{const i=(py*w+px)*4;d[i]=fill[0];d[i+1]=fill[1];d[i+2]=fill[2];d[i+3]=255};const stack=[[x,y]];while(stack.length){const [sx,sy]=stack.pop();if(!matches(sx,sy))continue;let lx=sx;while(lx>=0&&matches(lx,sy))lx--;lx++;let spanUp=false,spanDown=false;for(let px=lx;px<w&&matches(px,sy);px++){paint(px,sy);if(sy>0){if(matches(px,sy-1)){if(!spanUp){stack.push([px,sy-1]);spanUp=true}}else spanUp=false}if(sy<h-1){if(matches(px,sy+1)){if(!spanDown){stack.push([px,sy+1]);spanDown=true}}else spanDown=false}}}ctx.putImageData(image,0,0)}
function updateZoomLabel(){const z=document.getElementById('zoomValue');if(z)z.textContent=Math.round(colorZoom*100)+'%'}
function applyColorZoom(next,anchor=null){if(!colorViewport||!colorCanvasWrap)return;const oldZoom=colorZoom;const oldSize=colorBaseDisplay*oldZoom;colorZoom=Math.max(1,Math.min(4,next));colorBaseDisplay=Math.min(600,Math.max(280,colorViewport.clientWidth-8));const newSize=colorBaseDisplay*colorZoom;let ax=colorViewport.clientWidth/2,ay=colorViewport.clientHeight/2;if(anchor){ax=anchor.x;ay=anchor.y}const contentX=(colorViewport.scrollLeft+ax)/(oldSize||colorBaseDisplay),contentY=(colorViewport.scrollTop+ay)/(oldSize||colorBaseDisplay);colorCanvasWrap.style.width=newSize+'px';colorCanvasWrap.style.height=newSize+'px';canvas.style.width=newSize+'px';canvas.style.height=newSize+'px';updateZoomLabel();if(oldZoom!==colorZoom){requestAnimationFrame(()=>{colorViewport.scrollLeft=Math.max(0,contentX*newSize-ax);colorViewport.scrollTop=Math.max(0,contentY*newSize-ay)})}}
function zoomColor(delta){applyColorZoom(colorZoom+delta)}
function resetColorZoom(){colorZoom=1;colorViewport.scrollLeft=0;colorViewport.scrollTop=0;applyColorZoom(1);requestAnimationFrame(()=>{colorViewport.scrollLeft=0;colorViewport.scrollTop=0})}
function pointerDistance(){const pts=[...colorPointers.values()];if(pts.length<2)return 0;return Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)}
function pointerMidpoint(){const pts=[...colorPointers.values()];if(pts.length<2)return{x:colorViewport.clientWidth/2,y:colorViewport.clientHeight/2};const r=colorViewport.getBoundingClientRect();return{x:(pts[0].x+pts[1].x)/2-r.left,y:(pts[0].y+pts[1].y)/2-r.top}}
colorViewport.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;colorViewport.setPointerCapture?.(e.pointerId);colorPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(colorPointers.size===1){colorDragMoved=false;colorDragStart={x:e.clientX,y:e.clientY,scrollLeft:colorViewport.scrollLeft,scrollTop:colorViewport.scrollTop,target:e.target}}else if(colorPointers.size===2){colorGesture={dist:pointerDistance(),zoom:colorZoom,mid:pointerMidpoint()};colorDragMoved=true}e.preventDefault()});
colorViewport.addEventListener('pointermove',e=>{if(!colorPointers.has(e.pointerId))return;colorPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(colorPointers.size>=2&&colorGesture){const d=pointerDistance();if(colorGesture.dist>0)applyColorZoom(colorGesture.zoom*(d/colorGesture.dist),pointerMidpoint());colorDragMoved=true;e.preventDefault();return}if(colorPointers.size===1&&colorDragStart&&colorZoom>1){const dx=e.clientX-colorDragStart.x,dy=e.clientY-colorDragStart.y;if(Math.hypot(dx,dy)>7)colorDragMoved=true;if(colorDragMoved){colorViewport.scrollLeft=colorDragStart.scrollLeft-dx;colorViewport.scrollTop=colorDragStart.scrollTop-dy;e.preventDefault()}}});
function endColorPointer(e){const wasOnly=colorPointers.size===1;const shouldPaint=wasOnly&&!colorDragMoved&&colorDragStart?.target===canvas;if(shouldPaint){const p=getPointerPos(e);fillAt(p.x,p.y)}colorPointers.delete(e.pointerId);if(colorPointers.size<2)colorGesture=null;if(colorPointers.size===0){colorDragStart=null;colorDragMoved=false}e.preventDefault()}
colorViewport.addEventListener('pointerup',endColorPointer);colorViewport.addEventListener('pointercancel',e=>{colorPointers.delete(e.pointerId);if(colorPointers.size<2)colorGesture=null;if(colorPointers.size===0){colorDragStart=null;colorDragMoved=false}});
window.addEventListener('resize',()=>{if(!document.getElementById('coloringModal').classList.contains('hidden'))applyColorZoom(colorZoom)});
function undoColoring(){if(!colorHistory.length)return toast('Nada para desfazer 😊');ctx.putImageData(colorHistory.pop(),0,0)}
function clearCanvas(){if(baseTemplate)drawBase();else{ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height)}toast('Desenho limpo!')}
function rewardArt(){const key='artReward'+new Date().toDateString();if(localStorage.getItem(key))return toast('Você já ganhou a estrela da pintura hoje 💗');localStorage.setItem(key,'1');addStars(1,'Pintura concluída! ⭐')}
function saveColoring(){const a=document.createElement('a');a.download='colorindo-com-a-elo.png';a.href=canvas.toDataURL('image/png');a.click();toast('Imagem pronta para salvar 💗')}

const ACH=[
 {icon:'⭐',name:'Primeira estrela',ok:()=>stars>=1},
 {icon:'🌈',name:'Exploradora',ok:()=>stars>=10},
 {icon:'👑',name:'Super Elo',ok:()=>stars>=25},
 {icon:'📚',name:'Leitora de Aventuras',ok:()=>readStories.length>=1},
 {icon:'🏆',name:'Mestre das Aventuras',ok:()=>readStories.length>=4},
 {icon:'🎨',name:'Artista do dia',ok:()=>!!localStorage.getItem('artReward'+new Date().toDateString())},
 {icon:'🧠',name:'Craque da Escolinha',ok:()=>stars>=40},
 {icon:'💗',name:'Missão do dia',ok:()=>!!localStorage.getItem(dailyKey)}
];
function renderBadges(){const baseUnlocked=ACH.filter(x=>x.ok()).length,medalUnlocked=MEDAL_GAMES.reduce((n,g)=>n+['easy','medium','hard'].filter(level=>hasGameMedal(g.id,level)).length,0),rpgUnlocked=getRpgMedals().length,unlocked=baseUnlocked+medalUnlocked+rpgUnlocked,total=ACH.length+MEDAL_GAMES.length*3+RPG_MEDALS.length;const html=ACH.map(x=>`<div class="badge ${x.ok()?'on':''}"><span>${x.icon}</span><strong>${x.name}</strong><small>${x.ok()?'Conquistada!':'Continue brincando'}</small></div>`).join('');const all=document.getElementById('allBadges');if(all)all.innerHTML=html;renderGameMedals();renderRpgMedals();const home=document.getElementById('achievementCountHome');if(home)home.textContent=unlocked;const u=document.getElementById('achievementUnlocked');if(u)u.textContent=unlocked;const t=document.getElementById('achievementTotal');if(t)t.textContent=total}


setupAppHistory();
renderStars();
renderStoryStrip();
renderLibrary();
renderPlaylists();
startQuiz('easy');
startMemory();
renderPalette();
renderColoringGallery();
chooseColoring(0);
renderBadges();
window.addEventListener('load',()=>setTimeout(()=>{const s=document.getElementById('splash');s.style.opacity='0';setTimeout(()=>s.remove(),450)},700));
if('serviceWorker' in navigator){
  navigator.serviceWorker.addEventListener('controllerchange',()=>{
    if(!sessionStorage.getItem('elo-v1-5-reloaded')){
      sessionStorage.setItem('elo-v1-5-reloaded','1');
      location.reload();
    }
  });
  navigator.serviceWorker.register('./sw.js?v=1.6.3',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});
}
