/* Dia a Dia da Elo — Bichinho da Elo v2 • integrado à v3.1.1 */
(function(){
'use strict';
const PET_KEY='eloVirtualPetV1';
const EGG_CARE_GOAL=5;
const EGG_COOLDOWN_MS=2*60*1000;
const SLEEP_DURATION_MS=2*60*1000;
const ACTION_COOLDOWNS={feed:45e3,bath:75e3,hygiene:60e3,play:60e3,love:45e3,sleep:120e3,study:90e3};
const SPECIES={
 unicorn:{label:'Unicórnio',defaultName:'Luma'},
 cat:{label:'Gatinho',defaultName:'Pipoca'},
 dog:{label:'Cachorrinho',defaultName:'Pingo'},
 bunny:{label:'Coelhinho',defaultName:'Nuvem'}
};
const ACCESSORIES=[
 {id:'none',icon:'✨',name:'Sem acessório',need:0},
 {id:'bow',icon:'🎀',name:'Laço',need:5},
 {id:'star',icon:'⭐',name:'Estrela',need:12},
 {id:'crown',icon:'👑',name:'Coroa',need:24}
];
const ACTIONS=[
 {id:'feed',icon:'🥣',label:'Comida'},
 {id:'bath',icon:'🚿',label:'Banho'},
 {id:'hygiene',icon:'🪥',label:'Higiene'},
 {id:'play',icon:'🎾',label:'Brincar'},
 {id:'love',icon:'💗',label:'Carinho'},
 {id:'sleep',icon:'🌙',label:'Dormir'},
 {id:'study',icon:'📚',label:'Estudar'}
];
function defaultPet(){return{stage:'egg',species:null,name:'Ovinho misterioso',eggCare:0,eggNextCareAt:0,careCount:0,hunger:86,energy:86,clean:86,fun:86,love:90,study:80,accessory:'none',sleepUntil:0,lastActions:{},lastSeen:Date.now(),lastDecayAt:Date.now(),rewards:{hatch:false,care10:false,care20:false}}}
function clamp(n){return Math.max(0,Math.min(100,Number(n)||0))}
function normalizePet(src){const d=defaultPet(),p=Object.assign(d,src||{});p.rewards=Object.assign({},d.rewards,src?.rewards||{});p.lastActions=Object.assign({},d.lastActions,src?.lastActions||{});if(!Number.isFinite(Number(p.study)))p.study=80;if(!Number.isFinite(Number(p.lastDecayAt)))p.lastDecayAt=Number(p.lastSeen)||Date.now();return p}
function rawLoad(){try{return normalizePet(JSON.parse(pget(PET_KEY)||'{}'))}catch(_){return defaultPet()}}
function persistPet(p,touch=true){if(touch)p.lastSeen=Date.now();pset(PET_KEY,JSON.stringify(p));return p}
function applyTimePassage(p){const now=Date.now();if(p.stage==='egg'){if(!p.lastDecayAt)p.lastDecayAt=now;return p}const last=Number(p.lastDecayAt||p.lastSeen||now),elapsed=Math.max(0,now-last);if(elapsed<60e3)return p;const hours=Math.min(24,elapsed/3600000);p.hunger=clamp(p.hunger-Math.min(55,hours*4));p.energy=clamp(p.energy-Math.min(42,hours*2.4));p.clean=clamp(p.clean-Math.min(48,hours*3));p.fun=clamp(p.fun-Math.min(42,hours*2.4));p.love=clamp(p.love-Math.min(25,hours*1.35));p.study=clamp(p.study-Math.min(45,hours*2.2));p.lastDecayAt=now;persistPet(p,false);return p}
function loadPet(){return applyTimePassage(rawLoad())}
function stageInfo(p){if(p.stage==='egg')return{key:'egg',label:'Ovinho',next:EGG_CARE_GOAL,pct:Math.min(100,p.eggCare/EGG_CARE_GOAL*100)};if(p.careCount<8)return{key:'baby',label:'Filhote',next:8,pct:p.careCount/8*100};if(p.careCount<20)return{key:'young',label:'Jovem',next:20,pct:(p.careCount-8)/12*100};return{key:'friend',label:'Companheiro',next:20,pct:100}}
function isSleeping(p){return p.stage!=='egg'&&Date.now()<Number(p.sleepUntil||0)}
function gradeText(p){return (clamp(p.study)/10).toFixed(1).replace('.',',')}
function moodText(p){if(isSleeping(p))return `${p.name} está dormindo... zZz 🌙`;if(p.clean<35)return `${p.name} está sujinho. Hora de banho ou higiene! 🫧`;if(p.energy<35)return `${p.name} está cansado e precisa dormir. 🌙`;if(p.hunger<35)return `${p.name} está com fome. Que tal uma comidinha? 🥣`;if(p.study<35)return `${p.name} quer estudar um pouquinho. A nota está ${gradeText(p)}. 📚`;const avg=(p.hunger+p.energy+p.clean+p.fun+p.love+p.study)/6;if(avg>84)return `${p.name} está radiante! ✨`;if(avg>68)return `${p.name} está muito bem e quer brincar.`;if(avg>52)return `${p.name} está tranquilo. Que tal um carinho?`;return `${p.name} quer um pouco de atenção. Escolha um cuidado abaixo 💗`}
function speciesPick(){const seed=(Date.now()+String(activeProfileId||'elo').split('').reduce((a,c)=>a+c.charCodeAt(0),0))%4;return Object.keys(SPECIES)[seed]}
function rewardCareMilestones(p){if(p.careCount>=10&&!p.rewards.care10){p.rewards.care10=true;if(typeof addStars==='function')addStars(1,'Seu bichinho cresceu com seus cuidados! +1 ⭐')}if(p.careCount>=20&&!p.rewards.care20){p.rewards.care20=true;if(typeof addStars==='function')addStars(2,'Virou um grande companheiro! +2 ⭐')}}
function visualAccessory(id){return id==='bow'?'🎀':id==='star'?'⭐':id==='crown'?'👑':''}
function formatWait(ms){const s=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(s/60),r=String(s%60).padStart(2,'0');return m>0?`${m}:${r}`:`0:${r}`}
function actionWait(p,id){return Math.max(0,Number(p.lastActions?.[id]||0)+Number(ACTION_COOLDOWNS[id]||0)-Date.now())}
function renderStats(p){const box=document.getElementById('petStats');if(!box)return;const arr=[['🥣','Fome',p.hunger,''],['⚡','Energia',p.energy,''],['🫧','Higiene',p.clean,''],['🎾','Diversão',p.fun,''],['💗','Carinho',p.love,''],['📚','Estudo',p.study,`Nota ${gradeText(p)}`]];box.innerHTML=arr.map(([ic,n,v,sub])=>`<div class="petStat"><span>${ic}</span><b>${n}</b>${sub?`<small>${sub}</small>`:''}<div class="petMeter"><i style="width:${Math.round(v)}%"></i></div></div>`).join('')}
function renderActions(p){const box=document.getElementById('petActions');if(!box)return;const sleeping=isSleeping(p);box.innerHTML=ACTIONS.map(a=>{const wait=actionWait(p,a.id),disabled=sleeping||wait>0;let sub=wait>0?formatWait(wait):'Pronto';if(sleeping)sub=a.id==='sleep'?`Dormindo ${formatWait(p.sleepUntil-Date.now())}`:'Esperando';return `<button ${disabled?'disabled':''} onclick="petAction('${a.id}')"><span>${a.icon}</span><b>${a.label}</b><small>${sub}</small></button>`}).join('')}
function renderAccessories(p){const box=document.getElementById('petAccessoryGrid');if(!box)return;box.innerHTML=ACCESSORIES.map(a=>{const ok=p.careCount>=a.need,on=p.accessory===a.id;return `<button class="petAccessoryBtn ${on?'on':''} ${ok?'':'locked'}" onclick="choosePetAccessory('${a.id}')"><span>${ok?a.icon:'🔒'}</span><b>${a.name}</b>${ok?'':`<small>${a.need} cuidados</small>`}</button>`}).join('')}
function renderEgg(p,st){const bubble=document.getElementById('petBubble'),btn=document.getElementById('eggCareBtn'),waitText=document.getElementById('eggCooldownText'),wait=Math.max(0,Number(p.eggNextCareAt||0)-Date.now());document.getElementById('eggCareText').textContent=`${p.eggCare}/${EGG_CARE_GOAL} cuidados`;document.getElementById('eggCareBar').style.width=`${st.pct}%`;if(btn){btn.disabled=wait>0;const sm=btn.querySelector('small');if(sm)sm.textContent=wait>0?`Próximo cuidado em ${formatWait(wait)}`:'Pode cuidar agora'}if(waitText)waitText.textContent=wait>0?`Espere ${formatWait(wait)} para cuidar novamente.`:'O ovo está pronto para receber um novo cuidado.';const msgs=['Cuide do ovo para descobrir quem vai nascer! 💗','O ovinho mexeu um pouquinho! ✨','Ele está ficando quentinho e feliz. 💗','Tem alguma coisa se mexendo aí dentro! 👀','Está quase na hora de nascer! ✨'];bubble.textContent=msgs[Math.min(p.eggCare,msgs.length-1)]}
function renderPet(){const p=loadPet(),st=stageInfo(p),egg=document.getElementById('petEgg'),creature=document.getElementById('petCreature'),eggBox=document.getElementById('petEggControls'),care=document.getElementById('petCareArea'),bubble=document.getElementById('petBubble'),stage=document.getElementById('petStageLabel'),name=document.getElementById('petNameLabel'),rename=document.getElementById('petRenameBtn'),screen=document.querySelector('#petPanel .petScreen');if(!egg||!creature)return;stage.textContent=st.label;name.textContent=p.name;rename.style.visibility=p.stage==='egg'?'hidden':'visible';if(p.stage==='egg'){screen?.classList.remove('sleeping');egg.classList.remove('hidden');creature.className='petCreature hidden';eggBox.classList.remove('hidden');care.classList.add('hidden');renderEgg(p,st);return}egg.classList.add('hidden');eggBox.classList.add('hidden');care.classList.remove('hidden');const sleeping=isSleeping(p);creature.className=`petCreature species-${p.species} stage-${st.key}`;if(p.clean<35)creature.classList.add('dirty');if(p.energy<35&&!sleeping)creature.classList.add('tired');if(sleeping)creature.classList.add('sleeping');if(p.study>=80)creature.classList.add('smart');screen?.classList.toggle('sleeping',sleeping);document.getElementById('petAccessory').textContent=visualAccessory(p.accessory);bubble.textContent=moodText(p);renderStats(p);renderActions(p);renderAccessories(p);document.getElementById('petGrowthText').textContent=st.key==='friend'?'Companheiro completo ✨':`Crescimento • ${st.label}`;document.getElementById('petGrowthSub').textContent=st.key==='friend'?`${p.careCount} cuidados • nota ${gradeText(p)}.`:`${p.careCount}/${st.next} cuidados • nota ${gradeText(p)}.`;document.getElementById('petGrowthBar').style.width=`${st.pct}%`}
window.renderPet=renderPet;
window.openPet=function(){openPanel('petPanel','home');renderPet()};
window.careForEgg=function(){const p=rawLoad();if(p.stage!=='egg')return renderPet();const now=Date.now(),wait=Math.max(0,Number(p.eggNextCareAt||0)-now);if(wait>0){toast(`Espere ${formatWait(wait)} para cuidar do ovo novamente 💗`);return}p.eggCare=Math.min(EGG_CARE_GOAL,Number(p.eggCare||0)+1);if(p.eggCare>=EGG_CARE_GOAL){p.stage='baby';p.species=speciesPick();p.name=SPECIES[p.species].defaultName;p.hunger=p.energy=p.clean=p.fun=p.love=92;p.study=82;p.eggNextCareAt=0;p.lastDecayAt=now;if(!p.rewards.hatch){p.rewards.hatch=true;if(typeof addStars==='function')addStars(2,'Seu bichinho nasceu! +2 ⭐')}persistPet(p);renderPet();const label=SPECIES[p.species].label;toast(`Nasceu um ${label}! 💗`);if(typeof speakText==='function')setTimeout(()=>speakText(`Que surpresa! Nasceu ${p.name}, seu novo ${label}.`),180);return}p.eggNextCareAt=now+EGG_COOLDOWN_MS;persistPet(p);renderPet();toast('Cuidado registrado! Agora o ovinho precisa descansar um pouquinho 💗')};
function react(cls){const el=document.getElementById('petCreature');if(!el)return;el.classList.remove('react','sleepy','cleanSparkle','loveBurst','studySparkle');void el.offsetWidth;el.classList.add(cls||'react');setTimeout(()=>{el.classList.remove('react','cleanSparkle','loveBurst','studySparkle');if(cls==='sleepy')setTimeout(()=>el.classList.remove('sleepy'),650)},700)}
window.petAction=function(action){const p=loadPet();if(p.stage==='egg')return careForEgg();if(isSleeping(p)){toast(`${p.name} está dormindo. Deixe descansar um pouquinho 🌙`);return}if(!ACTIONS.some(x=>x.id===action))return;const wait=actionWait(p,action);if(wait>0){toast(`Espere ${formatWait(wait)} para repetir esta ação.`);return}let msg='';if(action==='feed'){p.hunger=clamp(p.hunger+28);p.energy=clamp(p.energy+3);msg='Que delícia! 🥣';react('react')}else if(action==='bath'){p.clean=clamp(p.clean+32);p.love=clamp(p.love+4);msg='Banho tomado! Tudo limpinho ✨';react('cleanSparkle')}else if(action==='hygiene'){p.clean=clamp(p.clean+18);p.love=clamp(p.love+2);msg='Higiene em dia! 🪥✨';react('cleanSparkle')}else if(action==='play'){p.fun=clamp(p.fun+28);p.love=clamp(p.love+5);p.energy=clamp(p.energy-7);p.hunger=clamp(p.hunger-5);msg='Que brincadeira divertida! 🎾';react('react')}else if(action==='sleep'){p.energy=clamp(p.energy+30);p.hunger=clamp(p.hunger-3);p.sleepUntil=Date.now()+SLEEP_DURATION_MS;msg='Boa noite! A luz foi apagada 🌙';react('sleepy')}else if(action==='study'){p.study=clamp(p.study+22);p.fun=clamp(p.fun-2);p.energy=clamp(p.energy-3);msg=`Estudo concluído! Nota ${gradeText(p)} 📚`;react('studySparkle')}else{p.love=clamp(p.love+25);p.fun=clamp(p.fun+5);msg='Carinho recebido! 💗';react('loveBurst')}p.lastActions[action]=Date.now();p.careCount=Number(p.careCount||0)+1;rewardCareMilestones(p);persistPet(p);renderPet();const bubble=document.getElementById('petBubble');if(bubble)bubble.textContent=msg;toast(msg)};
window.renamePet=function(){const p=loadPet();if(p.stage==='egg')return;const val=(prompt('Qual será o nome do seu bichinho?',p.name)||'').trim().slice(0,16);if(!val)return;p.name=val;persistPet(p);renderPet();toast(`Agora ele se chama ${val} 💗`)};
window.choosePetAccessory=function(id){const p=loadPet(),a=ACCESSORIES.find(x=>x.id===id);if(!a)return;if(p.careCount<a.need)return toast(`Libera com ${a.need} cuidados 💗`);p.accessory=id;persistPet(p);renderPet();toast(`${a.name} escolhido! ✨`)};
window.petSpeakStatus=function(){const p=loadPet();if(typeof speakText!=='function')return;if(p.stage==='egg'){const wait=Math.max(0,Number(p.eggNextCareAt||0)-Date.now());speakText(wait>0?`Este é um ovinho misterioso. O próximo cuidado estará disponível em ${Math.ceil(wait/60000)} minutos.`:`Este é um ovinho misterioso. Cuide dele aos poucos para descobrir quem vai nascer.`)}else speakText(`${p.name} é seu bichinho virtual. ${moodText(p)} A nota de estudo é ${gradeText(p)}.`)};
const oldOpenPanelPet=window.openPanel;
window.openPanel=function(id,nav,fromHistory=false){oldOpenPanelPet(id,nav,fromHistory);if(id==='petPanel')renderPet()};
window.addEventListener('DOMContentLoaded',()=>{if(document.getElementById('petPanel')?.classList.contains('active'))renderPet();setInterval(()=>{if(document.getElementById('petPanel')?.classList.contains('active'))renderPet()},1000)});
})();
