/* Dia a Dia da Elo — v3.0.1: Mundo da Elo renovado */
(function(){
'use strict';
const V3_KEY='eloV3WorldState';
const V3_COLLECTIONS={
  stars:{icon:'⭐',name:'Estrelas',goal:12},bows:{icon:'🎀',name:'Laços',goal:6},unicorns:{icon:'🦄',name:'Unicórnios',goal:5},rainbows:{icon:'🌈',name:'Arco-íris',goal:5},stickers:{icon:'✨',name:'Adesivos',goal:12}
};
const ROOM_DECOR=[
 {id:'wallPink',kind:'wall',icon:'🩷',name:'Parede Rosa',need:0,className:''},{id:'wallBlue',kind:'wall',icon:'🩵',name:'Parede Céu',need:10,className:'wall-blue'},{id:'wallStars',kind:'wall',icon:'🌌',name:'Parede Estrelas',need:25,className:'wall-stars'},
 {id:'rainbow',kind:'art',icon:'🌈',name:'Quadro Arco-íris',need:0},{id:'stars',kind:'art',icon:'⭐',name:'Quadro Estrelas',need:18},{id:'heart',kind:'art',icon:'💗',name:'Quadro Coração',need:35},
 {id:'bedPink',kind:'bed',icon:'🛏️',name:'Cama Rosa',need:0},{id:'bedBlue',kind:'bed',icon:'🩵',name:'Cama Céu',need:20},{id:'bedStar',kind:'bed',icon:'⭐',name:'Cama Estrela',need:45},
 {id:'rugHeart',kind:'rug',icon:'💗',name:'Tapete Coração',need:0},{id:'rugRainbow',kind:'rug',icon:'🌈',name:'Tapete Arco-íris',need:14},{id:'rugCloud',kind:'rug',icon:'☁️',name:'Tapete Nuvem',need:32},
 {id:'unicorn',kind:'toy',icon:'🦄',name:'Unicórnio',need:0,value:'🦄'},{id:'teddy',kind:'toy',icon:'🧸',name:'Ursinho',need:15,value:'🧸'},{id:'cat',kind:'toy',icon:'🐱',name:'Gatinho',need:30,value:'🐱'}
];
const OUTFITS=[
 {id:'pink',icon:'🎀',name:'Look Rosa',need:0,badge:'🎀'},{id:'rainbow',icon:'🌈',name:'Look Arco-íris',need:10,badge:'🌈'},{id:'unicorn',icon:'🦄',name:'Fantasia Unicórnio',need:22,badge:'🦄'},{id:'artist',icon:'🎨',name:'Elo Artista',need:38,badge:'🎨'},{id:'star',icon:'⭐',name:'Elo Estrela',need:55,badge:'⭐'},{id:'adventure',icon:'🧭',name:'Elo Aventureira',need:75,badge:'🧭'}
];
function defaultV3(){return{collections:{stars:0,bows:0,unicorns:0,rainbows:0,stickers:0},secrets:[],room:{wall:'wallPink',art:'rainbow',bed:'bedPink',rug:'rugHeart',toy:'unicorn'},outfit:'pink',weekly:{key:'',opened:false},creativeDone:[],interactiveDone:[],familyRounds:0,schoolProgress:{colors:0,numbers:0,shapes:0,animals:0}}}
function v3Load(){try{return Object.assign(defaultV3(),JSON.parse(pget(V3_KEY)||'{}'))}catch(_){return defaultV3()}}
function v3Save(v){pset(V3_KEY,JSON.stringify(v));renderV3Counters()}
function v3Total(v=v3Load()){return Object.values(v.collections||{}).reduce((a,b)=>a+Number(b||0),0)}
function addCollectible(type,n=1,message){const v=v3Load();if(!(type in V3_COLLECTIONS))return;v.collections[type]=Math.min(V3_COLLECTIONS[type].goal,Number(v.collections[type]||0)+n);v3Save(v);if(message)toast(message);renderCollection();renderRoom();renderWardrobe();}
const WORLD_META={room:{title:'Quarto da Elo',sub:'Continue decorando seu cantinho'},school:{title:'Escolinha da Elo',sub:'Continue aprendendo brincando'},play:{title:'Jogos da Elo',sub:'Escolha uma nova brincadeira'},rpg:{title:'Reino das Estrelas',sub:'Continue sua aventura no RPG'},creative:{title:'Ateliê da Elo',sub:'Crie, pinte e invente'},cinema:{title:'Cinema da Elo',sub:'Veja vídeos e playlists'},library:{title:'Biblioteca',sub:'Continue uma história'},club:{title:'Clubinho da Elo',sub:'Veja o espaço especial'}};
function renderHomeContinue(){const id=pget('v3LastPlace')||'',m=WORLD_META[id],t=document.getElementById('continueTitle'),s=document.getElementById('continueSub');if(t)t.textContent=m?.title||'Escolha uma aventura';if(s)s.textContent=m?.sub||'O app lembra seu último lugar.'}
function renderV3Counters(){const v=v3Load(),el=document.getElementById('collectionHomeCount');if(el)el.textContent=`${v3Total(v)} itens`;const wk=document.getElementById('weeklySurpriseStatus');if(wk)wk.textContent=v.weekly?.opened&&v.weekly.key===weekKey()?'Já descoberta ✓':'Toque para abrir';renderHomeContinue();}
window.renderV3Counters=renderV3Counters;
window.openContinueSpot=function(){const p=pget('v3LastPlace');if(p&&WORLD_META[p])openWorldPlace(p);else eloGuideSay('Escolha um lugar no mapa e eu vou lembrar para você continuar depois!')};

window.eloGuideSay=function(text){const b=document.getElementById('eloGuideText');if(b)b.textContent=text;if(typeof speakText==='function')speakText(text)};
window.worldPlaceSpeak=function(text){if(getActiveProfile().ageRange==='3-5'&&typeof speakText==='function')speakText(text)};
window.openWorldPlace=function(place){const map={room:['roomPanel','home','Vamos para casa! Você pode decorar o quarto e trocar o visual da Elo.'],school:['learnPanel','learn','Hora de aprender brincando!'],play:['playPanel','play','Escolha um jogo e divirta-se!'],rpg:['rpg',null,'O portal do Reino das Estrelas está aberto!'],creative:['createPanel','create','Vamos criar alguma coisa bem legal!'],cinema:['watchPanel','watch','Pegue a pipoca! O Cinema da Elo vai começar.'],library:['storiesPanel','stories','Na biblioteca, cada história é uma aventura.'],club:['clubPanel','club','Bem-vinda ao Clubinho da Elo!']};const a=map[place];if(!a)return;pset('v3LastPlace',place);renderHomeContinue();eloGuideSay(a[2]);if(a[0]==='rpg')setTimeout(()=>openRpg(),180);else setTimeout(()=>openPanel(a[0],a[1]),140)};
window.findWorldSecret=function(id){const typeMap={star:'stars',unicorn:'unicorns',bow:'bows'},v=v3Load();if(v.secrets.includes(id))return toast('Você já encontrou este segredo 💗');v.secrets.push(id);v3Save(v);addCollectible(typeMap[id],1,`Segredo encontrado! ${V3_COLLECTIONS[typeMap[id]].icon}`);addStars(1,'Você encontrou um segredo! +1 ⭐')};

function renderCollection(){const root=document.getElementById('collectionGrid');if(!root)return;const v=v3Load();root.innerHTML=Object.entries(V3_COLLECTIONS).map(([id,c])=>{const n=Number(v.collections[id]||0),pct=Math.round(n/c.goal*100);return `<div class="collectionCard"><span>${c.icon}</span><b>${c.name}</b><small>${n}/${c.goal}</small><div class="collectionMeter"><i style="width:${pct}%"></i></div></div>`}).join('')}
window.renderCollection=renderCollection;

function roomUnlocked(item){return stars>=item.need}
function renderRoom(){
 const room=document.getElementById('eloRoom'),grid=document.getElementById('roomDecorGrid');if(!room||!grid)return;
 const v=v3Load();v.room=v.room||{};v.room.wall=v.room.wall||'wallPink';v.room.art=v.room.art||'rainbow';v.room.bed=v.room.bed||'bedPink';v.room.rug=v.room.rug||'rugHeart';v.room.toy=v.room.toy||'unicorn';
 room.classList.remove('wall-blue','wall-stars');const wall=ROOM_DECOR.find(x=>x.id===v.room.wall);if(wall?.className)room.classList.add(wall.className);
 const art=ROOM_DECOR.find(x=>x.id===v.room.art),toy=ROOM_DECOR.find(x=>x.id===v.room.toy),bed=ROOM_DECOR.find(x=>x.id===v.room.bed),rug=ROOM_DECOR.find(x=>x.id===v.room.rug);
 const artEl=room.querySelector('.roomWallArt'),toyEl=room.querySelector('.roomToy'),bedEl=room.querySelector('.roomBed'),rugEl=room.querySelector('.roomRug');
 if(artEl)artEl.className=`roomWallArt art-${art?.id||'rainbow'}`;
 if(toyEl){toyEl.className=`roomToy toy-${toy?.id||'unicorn'}`;toyEl.textContent=toy?.value||'🦄'}
 if(bedEl)bedEl.className=`roomBed ${bed?.id==='bedBlue'?'bed-blue':bed?.id==='bedStar'?'bed-star':'bed-pink'}`;
 if(rugEl)rugEl.className=`roomRug ${rug?.id==='rugRainbow'?'rug-rainbow':rug?.id==='rugCloud'?'rug-cloud':'rug-heart'}`;
 grid.innerHTML=ROOM_DECOR.map(it=>{const on=v.room[it.kind]===it.id,unlock=roomUnlocked(it);return `<button class="decorItem ${on?'on':''} ${unlock?'':'locked'}" onclick="selectRoomDecor('${it.id}')"><span>${unlock?it.icon:'🔒'}</span><b>${it.name}</b><small>${unlock?(on?'Usando':'Usar'):`Libera com ${it.need} ⭐`}</small></button>`}).join('');
}window.renderRoom=renderRoom;
window.selectRoomDecor=function(id){const it=ROOM_DECOR.find(x=>x.id===id);if(!it)return;if(!roomUnlocked(it))return toast(`Este item libera com ${it.need} estrelas ⭐`);const v=v3Load();v.room[it.kind]=it.id;v3Save(v);renderRoom();if(typeof speakText==='function'&&getActiveProfile().ageRange==='3-5')speakText(it.name)};

function renderWardrobe(){const grid=document.getElementById('wardrobeGrid');if(!grid)return;const v=v3Load(),active=OUTFITS.find(x=>x.id===v.outfit)||OUTFITS[0];const p=document.getElementById('wardrobeElo'),n=document.getElementById('wardrobeName');if(p)p.textContent=`👧${active.badge}`;if(n)n.textContent=active.name;grid.innerHTML=OUTFITS.map(o=>{const unlocked=stars>=o.need,on=v.outfit===o.id;return `<button class="wardrobeItem ${on?'on':''} ${unlocked?'':'locked'}" onclick="equipV3Outfit('${o.id}')"><span>${unlocked?o.icon:'🔒'}</span><b>${o.name}</b><small>${unlocked?(on?'Vestindo':'Vestir'):`Libera com ${o.need} ⭐`}</small></button>`}).join('')}
window.renderWardrobe=renderWardrobe;
window.equipV3Outfit=function(id){const o=OUTFITS.find(x=>x.id===id);if(!o)return;if(stars<o.need)return toast(`Este look libera com ${o.need} estrelas ⭐`);const v=v3Load();v.outfit=id;v3Save(v);renderWardrobe();toast(`${o.name} equipado! 👗`)};

const CREATIVE={pizza:{title:'Monte sua pizza',main:'🍕',choices:['🍅','🧀','🌽','🫒','🍄','🥦']},cake:{title:'Decore o bolo',main:'🎂',choices:['🍓','⭐','🌈','💗','🍒','🍫']},toy:{title:'Monte um brinquedo maluco',main:'🤖',choices:['⚙️','🛞','🚀','🎀','⭐','🧲']},pet:{title:'Cuide do bichinho',main:'🐶',choices:['🥣','🦴','🫧','🎾','💗','🎀']}};
let creativeType='pizza',creativeItems=[];
window.selectCreative=function(type){if(!CREATIVE[type])return;creativeType=type;creativeItems=[];renderCreative()};
function renderCreative(){const root=document.getElementById('creativeWorkspace');if(!root)return;const c=CREATIVE[creativeType];root.innerHTML=`<h3 style="text-align:center;margin:2px 0 10px">${c.title}</h3><div class="creativeCanvas"><div class="creativeMain">${c.main}</div>${creativeItems.map((x,i)=>`<span class="creativeAdded" style="left:${15+(i*17)%70}%;top:${18+(i*23)%62}%">${x}</span>`).join('')}</div><div class="creativeChoices">${c.choices.map(x=>`<button onclick="addCreativeItem('${x}')">${x}</button>`).join('')}</div><div class="creativeDone"><button class="btn" onclick="finishCreative()">Terminei ✨</button> <button class="btn secondary" onclick="selectCreative('${creativeType}')">Limpar</button></div>`}
window.renderCreative=renderCreative;
window.addCreativeItem=function(x){if(creativeItems.length>=8)return toast('Já ficou cheio de detalhes! ✨');creativeItems.push(x);renderCreative()};
window.finishCreative=function(){if(creativeItems.length<2)return toast('Coloque pelo menos dois detalhes 😊');const v=v3Load(),first=!v.creativeDone.includes(creativeType);if(first)v.creativeDone.push(creativeType);v3Save(v);if(first){addCollectible('stickers',1,'Novo adesivo para a coleção! ✨');addStars(1,'Criação concluída! +1 ⭐')}else toast('Ficou lindo! 💗')};

const FAMILY={
 guess:['Imite um animal sem falar. A outra pessoa tenta adivinhar!','Pense em uma fruta e dê três pistas.','Faça um som de um objeto da casa. Quem adivinha?','Descreva uma cor sem dizer o nome dela.'],
 coop:['Encontrem juntos 3 coisas redondas perto de vocês.','Façam uma torre com 5 objetos seguros.','Inventem juntos um cumprimento engraçado.','Escolham uma música e façam uma dança de 20 segundos.'],
 draw:['Uma pessoa desenha uma cabeça e passa para a outra completar o corpo.','Um escolhe um animal e o outro acrescenta um cenário.','Façam juntos um desenho usando apenas círculos e linhas.','Cada pessoa acrescenta 3 detalhes ao mesmo desenho.']
};
let familyType='',familyTurn=1;
window.startFamilyGame=function(type){familyType=type;familyTurn=1;renderFamilyPrompt()};
function renderFamilyPrompt(){const box=document.getElementById('familyGameBox');if(!box||!FAMILY[familyType])return;const arr=FAMILY[familyType],prompt=arr[Math.floor(Math.random()*arr.length)];box.innerHTML=`<span class="familyTurn">${familyType==='coop'?'JUNTOS':`VEZ ${familyTurn}`}</span><div class="familyPrompt">${prompt}</div><button class="btn" onclick="nextFamilyPrompt()">Conseguimos! ⭐</button>`}
window.nextFamilyPrompt=function(){const v=v3Load();v.familyRounds=Number(v.familyRounds||0)+1;v3Save(v);familyTurn=familyTurn===1?2:1;if(v.familyRounds===3){addCollectible('rainbows',1,'Família unida! Novo arco-íris 🌈');addStars(1,'Brincadeira em família! +1 ⭐')}renderFamilyPrompt()};

const INTERACTIVE=[
 {id:'forest',icon:'🌳🦄',title:'O Caminho do Unicórnio',start:'Elo encontra duas trilhas perto da floresta. Qual caminho ela escolhe?',choices:[['🌸 Trilha das flores','flowers'],['🌙 Trilha brilhante','moon']],nodes:{flowers:{text:'As flores começam a mexer. Elo encontra um passarinho que precisa de ajuda.',choices:[['🐦 Ajudar o passarinho','kind'],['🔎 Procurar o unicórnio','search']]},moon:{text:'Pequenas estrelas iluminam o caminho até uma ponte mágica.',choices:[['🌉 Atravessar a ponte','brave'],['🎵 Chamar com uma música','song']]},kind:{end:'Elo ajuda o passarinho e ele mostra um atalho. No fim, ela encontra o unicórnio! 💗'},search:{end:'Elo segue pegadas brilhantes e encontra o unicórnio escondido entre as árvores! 🦄'},brave:{end:'Do outro lado da ponte, o unicórnio esperava por uma amiga corajosa. ✨'},song:{end:'O unicórnio reconhece a música e aparece dançando. 🎵🦄'}}},
 {id:'castle',icon:'🏰⭐',title:'O Castelo das Estrelas',start:'Uma porta do castelo está fechada. Elo encontra dois objetos. Qual usa primeiro?',choices:[['🗝️ Chave dourada','key'],['🔮 Cristal rosa','crystal']],nodes:{key:{text:'A chave abre uma sala cheia de quadros.',choices:[['🖼️ Olhar os quadros','art'],['🚪 Seguir pela porta','door']]},crystal:{text:'O cristal revela pegadas invisíveis no chão.',choices:[['👣 Seguir pegadas','steps'],['✨ Fazer o cristal brilhar','shine']]},art:{end:'Um quadro secreto se abre e revela uma estrela guardada há muitos anos! ⭐'},door:{end:'Elo encontra uma biblioteca e descobre um livro mágico sobre amizade. 📚'},steps:{end:'As pegadas levam até um jardim secreto no alto do castelo. 🌷'},shine:{end:'A luz do cristal acende todas as estrelas do castelo. 🌟'}}},
 {id:'garden',icon:'🌱🌈',title:'O Jardim Surpresa',start:'Elo encontra uma sementinha. Onde ela deve plantar?',choices:[['☀️ Perto do sol','sun'],['💧 Perto da fonte','water']],nodes:{sun:{text:'A terra está quentinha. O que Elo faz agora?',choices:[['💦 Regar','grow'],['🎶 Cantar','sing']]},water:{text:'A fonte faz a semente brilhar.',choices:[['🌱 Esperar','wait'],['🪴 Levar para um vaso','pot']]},grow:{end:'Nasce uma flor enorme com as cores do arco-íris! 🌈'},sing:{end:'A música faz brotar pequenas flores que dançam com a Elo. 🌸'},wait:{end:'Com paciência, nasce uma árvore cheia de estrelinhas. ⭐'},pot:{end:'No quarto da Elo, a plantinha cresce e vira uma amiga verde. 🪴'}}}
];
let storyState=null;
function renderInteractiveList(){const list=document.getElementById('interactiveStoryList'),play=document.getElementById('interactiveStoryPlay');if(!list||!play)return;play.classList.add('hidden');list.classList.remove('hidden');list.innerHTML=INTERACTIVE.map(s=>`<button class="interactiveStoryCard" onclick="startInteractiveStory('${s.id}')"><span>${s.icon}</span><div><b>${s.title}</b><small>Escolha o caminho e descubra finais diferentes.</small></div><i>›</i></button>`).join('')}
window.renderInteractiveList=renderInteractiveList;
window.startInteractiveStory=function(id){const story=INTERACTIVE.find(x=>x.id===id);if(!story)return;storyState={story,node:null};document.getElementById('interactiveStoryList')?.classList.add('hidden');document.getElementById('interactiveStoryPlay')?.classList.remove('hidden');renderInteractiveNode()};
function renderInteractiveNode(){const box=document.getElementById('interactiveStoryPlay');if(!box||!storyState)return;const {story,node}=storyState,content=node?story.nodes[node]:null;if(content?.end){box.innerHTML=`<div class="interactivePlayCard"><div class="interactiveScene">${story.icon}</div><h3>${story.title}</h3><p class="storyResult">${content.end}</p><button class="btn" onclick="finishInteractiveStory()">Finalizar ⭐</button></div>`;if(typeof speakText==='function'&&getActiveProfile().ageRange==='3-5')setTimeout(()=>speakText(content.end),180);return}const text=content?.text||story.start,choices=content?.choices||story.choices;box.innerHTML=`<div class="interactivePlayCard"><button class="smallBtn" onclick="renderInteractiveList()">‹ Histórias</button><div class="interactiveScene">${story.icon}</div><h3>${story.title}</h3><p class="storyResult">${text}</p><div class="interactiveChoices">${choices.map(c=>`<button onclick="chooseInteractive('${c[1]}')">${c[0]}</button>`).join('')}</div></div>`;if(typeof speakText==='function'&&getActiveProfile().ageRange==='3-5')setTimeout(()=>speakText(text),180)}
window.chooseInteractive=function(node){if(!storyState)return;storyState.node=node;renderInteractiveNode()};
window.finishInteractiveStory=function(){if(!storyState)return;const v=v3Load(),id=storyState.story.id,first=!v.interactiveDone.includes(id);if(first)v.interactiveDone.push(id);v3Save(v);if(first){addCollectible('rainbows',1,'Você ganhou um arco-íris da história! 🌈');addStars(2,'História interativa concluída! +2 ⭐')}storyState=null;renderInteractiveList()};

function weekKey(){const d=new Date(),jan1=new Date(d.getFullYear(),0,1),week=Math.ceil((((d-jan1)/86400000)+jan1.getDay()+1)/7);return `${d.getFullYear()}-W${week}`}
function ensureWeeklyOverlay(){let ov=document.getElementById('weeklyOverlay');if(ov)return ov;ov=document.createElement('div');ov.id='weeklyOverlay';ov.className='weeklyOverlay hidden';ov.innerHTML='<div class="weeklyCard"><div class="weeklyGift">🎁</div><h2>Surpresa da semana</h2><p id="weeklyText">Uma pequena surpresa para brincar e explorar.</p><button id="weeklyOpenBtn" class="btn" onclick="claimWeeklySurprise()">Abrir presente</button><button class="btn secondary" style="margin-top:8px" onclick="closeWeeklySurprise()">Fechar</button></div>';document.body.appendChild(ov);return ov}
window.openWeeklySurprise=function(){const ov=ensureWeeklyOverlay(),v=v3Load(),opened=v.weekly?.opened&&v.weekly.key===weekKey(),txt=document.getElementById('weeklyText'),btn=document.getElementById('weeklyOpenBtn');if(txt)txt.textContent=opened?'A surpresa desta semana já foi descoberta. Volte quando houver uma nova!':'Tem uma descoberta esperando por você!';if(btn){btn.disabled=opened;btn.textContent=opened?'Já aberta ✓':'Abrir presente'}ov.classList.remove('hidden')};
window.closeWeeklySurprise=function(){document.getElementById('weeklyOverlay')?.classList.add('hidden')};
window.claimWeeklySurprise=function(){const v=v3Load(),key=weekKey();if(v.weekly?.opened&&v.weekly.key===key)return;const types=['bows','unicorns','rainbows','stickers'],sum=[...key].reduce((a,c)=>a+c.charCodeAt(0),0),type=types[sum%types.length];v.weekly={key,opened:true};v3Save(v);addCollectible(type,1,`Surpresa: ${V3_COLLECTIONS[type].icon} ${V3_COLLECTIONS[type].name}!`);addStars(1,'Surpresa da semana! +1 ⭐');const txt=document.getElementById('weeklyText');if(txt)txt.textContent=`Você encontrou ${V3_COLLECTIONS[type].icon} para sua coleção!`;const btn=document.getElementById('weeklyOpenBtn');if(btn){btn.disabled=true;btn.textContent='Aberta ✓'}};

// Atividades curtas e dificuldade automática.
let v3QuizFirstTry=true,v3QuizHadMistake=false,v3KidHadMistake=false;
function adaptiveSchoolLevel(){const age=getSchoolAge(),skill=Number(pget('v3SchoolSkill')||0);if(age==='9-11')return skill>=1?'hard':'medium';return skill>=1?'medium':'easy'}
window.renderSchoolChallenges=function(){const controls=document.getElementById('schoolControls'),info=document.getElementById('schoolAgeInfo');if(!controls||!info)return;const age=getSchoolAge();info.innerHTML=`<div class="schoolAgeBadge">🎂 ${age.replace('-', '–')} anos</div>`;if(age==='3-5'){controls.innerHTML=`<p class="muted">A Elo fala. A criança olha e toca, sem precisar ler.</p><div class="kidSchoolCats">${Object.entries(SCHOOL_KID_SETS).map(([id,s])=>`<button class="chip ${schoolKidCategory===id?'on':''}" onclick="startKidSchool('${id}')" onpointerdown="speakText('${escapeHtml(s.name)}')"><span style="font-size:24px">${s.icon}</span></button>`).join('')}</div>`;startKidSchool(schoolKidCategory,true)}else{const level=adaptiveSchoolLevel();controls.innerHTML=`<p class="muted">Rodadas curtas de 5 desafios. A dificuldade muda sozinha conforme o desempenho.</p><div class="schoolAdaptivePill">✨ Dificuldade automática • ${level==='hard'?'Desafio':level==='medium'?'Intermediária':'Inicial'}</div>`;startQuiz(level)}};
window.startKidSchool=function(category='colors',silent=false){schoolKidCategory=category;schoolKidRound=0;schoolKidScore=0;schoolKidLocked=false;v3KidHadMistake=false;document.querySelectorAll('.kidSchoolCats .chip').forEach((b,i)=>b.classList.toggle('on',Object.keys(SCHOOL_KID_SETS)[i]===category));renderKidSchoolQuestion(silent)};
window.renderKidSchoolQuestion=function(silent=false){const box=document.getElementById('quiz'),set=SCHOOL_KID_SETS[schoolKidCategory];if(!box||!set)return;if(schoolKidRound>=5){const v=v3Load();v.schoolProgress=v.schoolProgress||{};v.schoolProgress[schoolKidCategory]=Math.round(schoolKidScore/5*100);v3Save(v);box.innerHTML=`<div class="kidSchoolEnd"><div>🏅⭐</div><b>Terminou!</b><button class="btn" onclick="startKidSchool('${schoolKidCategory}')">🔁</button></div>`;addStars(1,'Escolinha concluída! ⭐');trackActivity('school');return}schoolKidLocked=false;v3KidHadMistake=false;const correct=set.items[Math.floor(Math.random()*set.items.length)],others=shuffle(set.items.filter(x=>x[0]!==correct[0])).slice(0,2),opts=shuffle([correct,...others]);box.dataset.correct=correct[0];box.innerHTML=`<div class="kidSchoolActivity"><div class="kidListenPulse">👂</div><div class="kidSchoolOptions">${opts.map(o=>`<button class="kidSchoolChoice" data-value="${escapeHtml(o[0])}" onclick="answerKidSchool(this)">${kidOptionVisual(schoolKidCategory,o)}</button>`).join('')}</div><div class="kidSchoolDots">${schoolKidRound+1}/5</div></div>`;if(!silent)setTimeout(()=>speakText(`Toque em ${correct[0]}`),250)};
window.answerKidSchool=function(btn){if(schoolKidLocked)return;const box=document.getElementById('quiz'),correct=box.dataset.correct,val=btn.dataset.value;speakText(val);if(val!==correct){v3KidHadMistake=true;btn.classList.add('bad');setTimeout(()=>{btn.classList.remove('bad');speakText(`Toque em ${correct}`)},500);return}schoolKidLocked=true;if(!v3KidHadMistake)schoolKidScore++;btn.classList.add('good');setTimeout(()=>speakText(`Muito bem! ${correct}`),120);schoolKidRound++;setTimeout(()=>renderKidSchoolQuestion(false),850)};
window.startQuiz=function(level=adaptiveSchoolLevel()){quizLevel=level;quizDeck=shuffle(QUESTIONS[level]).slice(0,5);quizPos=0;quizCorrect=0;v3QuizHadMistake=false;renderQuiz()};
window.renderQuiz=function(){const box=document.getElementById('quiz');if(!box)return;if(quizPos>=quizDeck.length){const age=getSchoolAge(),ratio=quizCorrect/5;let skill=Number(pget('v3SchoolSkill')||0);if(ratio>=.8)skill=Math.min(2,skill+1);else if(ratio<=.4)skill=Math.max(0,skill-1);pset('v3SchoolSkill',skill);const reward=Math.max(1,Math.floor(quizCorrect/2));box.innerHTML=`<div class="quizEnd"><strong>${quizCorrect}/5 de primeira 🎉</strong><p class="muted">A próxima rodada será ajustada automaticamente.</p><button class="btn" onclick="renderSchoolChallenges()">Nova rodada</button></div>`;addStars(reward,`Escolinha concluída! +${reward} ⭐`);trackActivity('school');return}const q=quizDeck[quizPos];v3QuizHadMistake=false;box.innerHTML=`<div class="quizTop"><span class="quizProgress">Desafio ${quizPos+1}/5 • ${q[3]}</span><span class="quizProgress">De primeira: ${quizCorrect}</span></div><div class="quiz-q">${q[0]}</div><div class="answers">${q[1].map((x,i)=>`<button class="ans" onclick="answerQuiz(${i})">${x}</button>`).join('')}</div>`};
window.answerQuiz=function(i){const q=quizDeck[quizPos];if(i===q[2]){if(!v3QuizHadMistake)quizCorrect++;toast('Acertou! ⭐');quizPos++;setTimeout(renderQuiz,250)}else{v3QuizHadMistake=true;toast('Quase! Tente outra resposta 😊')}};

// Inglês: sessões menores + tipos adaptados ao domínio atual.
window.startEnglishPractice=function(id,review=false){englishWorldId=id;englishMode='practice';englishCorrect=0;englishPos=0;englishAnswered=false;const w=ENGLISH_WORLDS[id];let items=review?englishWeakItems(id):shuffle(w.items),limit=englishAge==='3-5'?5:6;items=items.slice(0,Math.min(limit,items.length));let types;if(englishAge==='3-5')types=['listen'];else{const avg=items.reduce((s,it)=>s+englishMastery(id,it.id),0)/Math.max(1,items.length);if(englishAge==='6-8')types=avg<1?['listen','choose']:avg<2?['choose','listen','write']:['write','scramble','listen'];else types=avg<1?['listen','choose','write']:avg<2?['write','scramble','sentence']:['sentence','translate','write','scramble']}englishSession=items.map((it,i)=>({item:it,type:types[i%types.length]}));englishSession=shuffle(englishSession);renderEnglishActivity()};

function renderParentV3(){const root=document.getElementById('v3ParentProgress');if(!root)return;const v=v3Load(),sp=v.schoolProgress||{},age=getActiveProfile().ageRange||'6-8';let mastered=0;try{mastered=ENGLISH_WORLD_ORDER.reduce((sum,id)=>sum+ENGLISH_WORLDS[id].items.filter(it=>englishMastery(id,it.id,age)>=3).length,0)}catch(_){}root.innerHTML=`<div class="v3ParentMiniGrid"><span><b>${sp.colors||0}%</b>Cores</span><span><b>${sp.numbers||0}%</b>Números</span><span><b>${mastered}</b>Palavras dominadas</span><span><b>${v3Total(v)}</b>Colecionáveis</span></div><p style="margin:9px 0 0"><b>Universo v3:</b> ${v.creativeDone.length}/4 criações • ${v.interactiveDone.length}/${INTERACTIVE.length} histórias interativas • ${v.familyRounds||0} rodadas em família.</p>`}

// Hook seguro de navegação sem alterar o RPG restaurado.
const oldOpenPanel=window.openPanel;
window.openPanel=function(id,nav,fromHistory=false){oldOpenPanel(id,nav,fromHistory);if(id==='collectionPanel')renderCollection();if(id==='roomPanel')renderRoom();if(id==='wardrobePanel')renderWardrobe();if(id==='creativePanel')renderCreative();if(id==='familyPanel'&&!familyType){document.getElementById('familyGameBox').innerHTML='<p class="muted">Escolha uma brincadeira acima.</p>'}if(id==='interactiveStoriesPanel')renderInteractiveList();if(id==='parentsPanel')renderParentV3();};

// Coleções por marcos reais, sem recompensas a cada clique.
const oldAddStars=window.addStars;
window.addStars=function(n=1,msg){const before=stars;oldAddStars(n,msg);const after=stars;const milestones=[[10,'bows'],[25,'rainbows'],[45,'unicorns'],[70,'stickers']];for(const [m,t] of milestones){if(before<m&&after>=m)addCollectible(t,1,`Nova descoberta na coleção! ${V3_COLLECTIONS[t].icon}`)}renderV3Counters();renderWardrobe();renderRoom()};

// Amplia o painel dos pais já existente sem regressão.
const oldRenderParentV2=window.renderParentV2;
window.renderParentV2=function(){oldRenderParentV2();renderParentV3()};

function initV3(){renderV3Counters();renderCollection();renderRoom();renderWardrobe();renderCreative();renderInteractiveList();ensureWeeklyOverlay();document.querySelectorAll('[data-app-version]').forEach(el=>el.textContent='3.0.1');renderHomeContinue();if(!pget('tutorial-v301'))setTimeout(()=>showTutorialOnce('v301','Mundo da Elo renovado! 🌈',['A tela inicial agora é um mundo para explorar. Toque nos lugares para entrar.','Procure pequenos segredos escondidos pelo mapa. Eles entram nas suas coleções.','Decore o quarto, escolha roupas, crie coisas e brinque no Modo Família.','A Escolinha tem rodadas curtas e ajusta a dificuldade automaticamente.','A Surpresa da Semana é só uma descoberta divertida: não existe sequência diária nem prêmio perdido.']),950)}
window.addEventListener('DOMContentLoaded',initV3);
})();
